import type { MockAction, MockBuilding, MockComponent, MockFacility } from '../src/mock.js';

/**
 * Two facilities of a small Swedish housing company, shaped the way a real Planima
 * account is: å/ä/ö throughout, prices with öre, nullable fields genuinely null, and
 * one action deliberately parked outside the default window.
 */
export const FACILITIES: MockFacility[] = [
  {
    id: 10,
    name: 'Kvarteret Önskan',
    organizationId: 1,
    address: 'Storgatan 14',
    zip_code: '11122',
    region: 'Stockholm',
    tags: ['bostad'],
    residential_area: 4200,
    non_residential_area: 310,
    year_of_construction: 1968,
    description: 'Tre huskroppar kring en innergård.',
  },
  {
    id: 20,
    name: 'Åkerbacken 3',
    organizationId: 2,
    address: null,
    zip_code: null,
    region: 'Göteborg',
    tags: [],
    residential_area: null,
    non_residential_area: 1500,
    year_of_construction: 2004,
    description: null,
  },
];

export const BUILDINGS: MockBuilding[] = [
  { id: 101, name: 'Hus A', facility_id: 10, address: 'Storgatan 14', zip_code: '11122', region: 'Stockholm', year_of_construction: 1968 },
  { id: 102, name: 'Hus B', facility_id: 10, address: 'Storgatan 16', zip_code: '11122', region: 'Stockholm', year_of_construction: 1971 },
  { id: 201, name: 'Lagerbyggnad', facility_id: 20, address: null, zip_code: null, region: null, year_of_construction: null },
];

export const COMPONENTS: MockComponent[] = [
  { id: 1001, name: 'Yttertak', facility_id: 10, building_id: 101, component: 'Tak', category: 'Yttertak', type: 'Betongpannor', amount: 620, unit: 'm2' },
  { id: 1002, name: 'Fönster', facility_id: 10, building_id: 102, component: 'Fönster', category: 'Fasad', type: null, amount: 84, unit: 'st' },
  { id: 2001, name: 'Portar', facility_id: 20, building_id: 201, component: 'Port', category: 'Fasad', type: null, amount: null, unit: null },
];

export const ACTIONS: MockAction[] = [
  {
    id: 5001,
    name: 'Omläggning yttertak',
    facility_id: 10,
    year: 2027,
    status: 'planned',
    amount: 500,
    unit: 'm2',
    // A price with öre, so the float → decimal-string conversion has something to get
    // wrong: `1250000.5` must not become `1250000.50` or `1250000.499999`.
    unit_price: 2500.25,
    total_price: 1250000.5,
    total_price_incl_vat: 1562500.63,
    description: 'Byte av betongpannor och underlagspapp.',
    investment_rate: 0.8,
    vat_rate: 0.25,
    category: 'Yttertak',
    location: 'Kvarteret Önskan',
    building: 'Hus A',
    building_id: 101,
    component_id: 1001,
    is_energy_saving: false,
    co2_equivalent: 18400.5,
    final_cost: null,
    tags: ['tak', 'Q3'],
  },
  {
    id: 5002,
    name: 'Fasadmålning',
    facility_id: 10,
    year: 2026,
    status: 'decided',
    amount: 1,
    unit: 'st',
    unit_price: 480000,
    total_price: 480000,
    total_price_incl_vat: 600000,
    // Explicitly null, not absent — the distinction that broke connector-fortnox.
    description: null,
    investment_rate: 0,
    vat_rate: 0.25,
    category: 'Fasad',
    location: 'Kvarteret Önskan',
    building: 'Hus B',
    building_id: 102,
    component_id: null,
    is_energy_saving: false,
    co2_equivalent: null,
    final_cost: null,
    tags: [],
  },
  {
    id: 5003,
    name: 'Byte till energiglas',
    facility_id: 10,
    year: 2029,
    status: 'prioritized',
    amount: 84,
    unit: 'st',
    unit_price: 9500,
    total_price: 798000,
    total_price_incl_vat: 997500,
    description: 'Fönsterbyte, U-värde 0,9.',
    investment_rate: 1,
    vat_rate: 0.25,
    category: 'Fasad',
    location: 'Kvarteret Önskan',
    building: 'Hus B',
    building_id: 102,
    component_id: 1002,
    is_energy_saving: true,
    co2_equivalent: -42000,
    final_cost: null,
    tags: ['energi'],
  },
  {
    id: 5004,
    name: 'Asfaltering parkering',
    facility_id: 20,
    year: 2026,
    status: 'completed',
    amount: 900,
    unit: 'm2',
    unit_price: 410,
    total_price: 369000,
    total_price_incl_vat: 461250,
    description: null,
    investment_rate: 0.5,
    vat_rate: 0.25,
    category: 'Mark',
    location: 'Åkerbacken 3',
    building: null,
    building_id: null,
    component_id: null,
    is_energy_saving: false,
    co2_equivalent: null,
    final_cost: 372500.75,
    tags: ['mark'],
  },
  {
    id: 5005,
    name: 'Portbyte',
    facility_id: 20,
    year: 2030,
    status: 'deferred',
    amount: 4,
    unit: 'st',
    unit_price: 62000,
    total_price: 248000,
    total_price_incl_vat: 310000,
    description: null,
    investment_rate: 1,
    vat_rate: 0.25,
    category: 'Fasad',
    location: 'Åkerbacken 3',
    building: 'Lagerbyggnad',
    building_id: 201,
    component_id: 2001,
    is_energy_saving: false,
    co2_equivalent: null,
    final_cost: null,
    tags: [],
  },
  {
    /**
     * Outside the 2026–2030 window on purpose.
     *
     * A maintenance plan routinely runs 30 years out, and the far years are the ones
     * that move every time a surveyor revisits. This row is what proves the window is
     * applied SERVER-side (`start_year`/`end_year`) rather than fetched and dropped —
     * the difference is a rate-limit budget spent on rows nobody keeps.
     */
    id: 5006,
    name: 'Stambyte',
    facility_id: 10,
    year: 2034,
    status: 'planned',
    amount: 1,
    unit: 'st',
    unit_price: 8400000,
    total_price: 8400000,
    total_price_incl_vat: 10500000,
    description: null,
    investment_rate: 1,
    vat_rate: 0.25,
    category: 'VA',
    location: 'Kvarteret Önskan',
    building: 'Hus A',
    building_id: 101,
    component_id: null,
    is_energy_saving: false,
    co2_equivalent: null,
    final_cost: null,
    tags: [],
  },
];
