/**
 * GENERATED by tools/emit-migrations.mts from journal.json — do not edit by hand.
 *
 * The journal is the record; this is the shape the kernel registers. Append a
 * migration by changing spec/model.ts and re-running:
 *
 *     pnpm --filter @substrat-run/demo-ticket0 emit:migrations
 *
 * CI re-emits with --check and fails on drift, so a hand-edit to shipped SQL is
 * caught here rather than at the next deploy.
 */
import type { SqlMigration } from '@substrat-run/kernel';

export const ticket0Migrations: SqlMigration[] = [
  {
    // add-ticket0_agent_profiles-and-13-more
    version: '0001',
    sql: `
      CREATE TABLE ticket0_agent_profiles (
        principal TEXT PRIMARY KEY NOT NULL,
        display_name TEXT NOT NULL,
        avatar_url TEXT,
        signature TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_ai_turns (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        message_id TEXT,
        model TEXT NOT NULL,
        input_tokens INTEGER NOT NULL,
        output_tokens INTEGER NOT NULL,
        cited_article_ids TEXT NOT NULL,
        confidence INTEGER,
        outcome TEXT NOT NULL CHECK (outcome IN ('drafted','answered','escalated','failed')),
        meter_entry_id TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_contacts (
        id TEXT PRIMARY KEY NOT NULL,
        external_id TEXT,
        principal TEXT,
        email TEXT,
        display_name TEXT,
        verified_at TEXT,
        created_at TEXT NOT NULL,
        UNIQUE (external_id)
      );

      CREATE TABLE ticket0_conversation_tags (
        conversation_id TEXT NOT NULL,
        tag TEXT NOT NULL,
        created_at TEXT NOT NULL,
        PRIMARY KEY (conversation_id, tag)
      );

      CREATE TABLE ticket0_conversations (
        id TEXT PRIMARY KEY NOT NULL,
        contact_id TEXT NOT NULL REFERENCES ticket0_contacts(id),
        channel TEXT NOT NULL CHECK (channel IN ('widget','email')),
        subject TEXT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('new','open','snoozed','resolved','closed')),
        assignee TEXT,
        priority TEXT NOT NULL CHECK (priority IN ('low','normal','urgent')),
        snoozed_until TEXT,
        first_public_reply_at TEXT,
        resolved_at TEXT,
        merged_into TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_csat (
        conversation_id TEXT PRIMARY KEY NOT NULL,
        score INTEGER NOT NULL,
        comment TEXT,
        submitted_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_desk_settings (
        id TEXT PRIMARY KEY NOT NULL,
        from_address TEXT NOT NULL,
        greeting TEXT NOT NULL,
        allowed_origins TEXT NOT NULL,
        verification_secret TEXT NOT NULL,
        business_hours TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_kb_articles (
        id TEXT PRIMARY KEY NOT NULL,
        source_id TEXT NOT NULL,
        url TEXT NOT NULL,
        title TEXT NOT NULL,
        heading_path TEXT NOT NULL,
        body TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        ingested_at TEXT NOT NULL,
        UNIQUE (source_id, url)
      );

      CREATE TABLE ticket0_kb_sources (
        id TEXT PRIMARY KEY NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('llms-txt','sitemap','markdown')),
        url TEXT NOT NULL,
        label TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('idle','ingesting','failed')),
        last_ingested_at TEXT,
        last_error TEXT,
        created_at TEXT NOT NULL,
        UNIQUE (url)
      );

      CREATE TABLE ticket0_messages (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        author_kind TEXT NOT NULL CHECK (author_kind IN ('contact','agent','assistant','system')),
        author_principal TEXT,
        visibility TEXT NOT NULL CHECK (visibility IN ('public','internal')),
        body_text TEXT NOT NULL,
        body_html TEXT,
        email_message_id TEXT,
        email_in_reply_to TEXT,
        delivered_at TEXT,
        cited_article_ids TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_notifications (
        id TEXT PRIMARY KEY NOT NULL,
        principal TEXT NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('assigned','replied','mentioned','snooze-woke','escalated')),
        conversation_id TEXT,
        read_at TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_saved_replies (
        id TEXT PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (title)
      );

      CREATE TABLE ticket0_usage_rates (
        meter_key TEXT NOT NULL,
        unit_price TEXT NOT NULL,
        currency TEXT NOT NULL,
        effective_from TEXT NOT NULL,
        PRIMARY KEY (meter_key, effective_from)
      );

      CREATE TABLE ticket0_widget_sessions (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        contact_id TEXT NOT NULL,
        origin TEXT NOT NULL,
        token_hash TEXT NOT NULL,
        started_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL,
        UNIQUE (token_hash)
      );
    `,
  },
  {
    // add-ticket0_widget_openings
    version: '0002',
    sql: `
      CREATE TABLE ticket0_widget_openings (
        id TEXT PRIMARY KEY NOT NULL,
        contact_id TEXT,
        origin TEXT NOT NULL,
        token_hash TEXT NOT NULL,
        started_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL,
        UNIQUE (token_hash)
      );
    `,
  },
  {
    // add-ticket0_widget_openings-user_agent-and-21-more
    version: '0003',
    sql: `
      ALTER TABLE ticket0_widget_openings ADD COLUMN user_agent TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN language TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN browser TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN browser_version TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN os TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN os_version TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN device TEXT CHECK (device IN ('desktop','mobile','tablet','bot','unknown'));

      ALTER TABLE ticket0_widget_openings ADD COLUMN country TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN region TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN city TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN timezone TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN user_agent TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN language TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN browser TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN browser_version TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN os TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN os_version TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN device TEXT CHECK (device IN ('desktop','mobile','tablet','bot','unknown'));

      ALTER TABLE ticket0_widget_sessions ADD COLUMN country TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN region TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN city TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN timezone TEXT;
    `,
  },
  {
    // add-ticket0_ai_turns-error
    version: '0004',
    sql: `
      ALTER TABLE ticket0_ai_turns ADD COLUMN error TEXT;
    `,
  },
  {
    // add-ticket0_desk_settings-assistant_autonomous
    version: '0005',
    sql: `
      ALTER TABLE ticket0_desk_settings ADD COLUMN assistant_autonomous INTEGER;
    `,
  },
  {
    // add-ticket0_signups
    version: '0006',
    sql: `
      CREATE TABLE ticket0_signups (
        id TEXT PRIMARY KEY NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('waitlist','newsletter')),
        email TEXT NOT NULL,
        note TEXT,
        state TEXT NOT NULL CHECK (state IN ('pending','confirmed','unsubscribed')),
        origin TEXT NOT NULL,
        confirm_token_hash TEXT,
        unsubscribe_token TEXT NOT NULL,
        requested_at TEXT NOT NULL,
        confirmed_at TEXT,
        unsubscribed_at TEXT,
        created_at TEXT NOT NULL,
        UNIQUE (kind, email)
      );
    `,
  },
  {
    // add-ticket0_conversations-follows
    version: '0007',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN follows TEXT;
    `,
  },
  {
    // add-ticket0_kb_sources-refresh_token_hash-and-3-more
    version: '0008',
    sql: `
      ALTER TABLE ticket0_kb_sources ADD COLUMN refresh_token_hash TEXT;

      ALTER TABLE ticket0_kb_sources ADD COLUMN refresh_token_hint TEXT;

      ALTER TABLE ticket0_kb_sources ADD COLUMN token_created_at TEXT;

      ALTER TABLE ticket0_kb_sources ADD COLUMN token_last_used_at TEXT;
    `,
  },
  {
    // add-ticket0_desk_settings-abandoned_after_days
    version: '0009',
    sql: `
      ALTER TABLE ticket0_desk_settings ADD COLUMN abandoned_after_days INTEGER;
    `,
  },
  {
    // add-ticket0_block_rules
    version: '0010',
    sql: `
      CREATE TABLE ticket0_block_rules (
        id TEXT PRIMARY KEY NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('email','domain','contact')),
        value TEXT NOT NULL,
        reason TEXT,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (kind, value)
      );
    `,
  },
  {
    // add-ticket0_conversations-first_assigned_at-and-2-more
    version: '0011',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN first_assigned_at TEXT;

      ALTER TABLE ticket0_desk_settings ADD COLUMN settings TEXT;

      ALTER TABLE ticket0_desk_settings ADD COLUMN round_robin_last TEXT;

      CREATE INDEX ticket0_conversations_waiting ON ticket0_conversations (assignee, created_at, id)
        WHERE assignee IS NULL AND first_assigned_at IS NULL AND state IN ('new', 'open') AND merged_into IS NULL;

      CREATE INDEX ticket0_ai_turns_by_conversation ON ticket0_ai_turns (conversation_id, created_at, id);

      CREATE INDEX ticket0_messages_public_by_conversation ON ticket0_messages (conversation_id, visibility, id);
    `,
  },
  {
    // add-ticket0_conversations-first_response_due_at-and-3-more
    version: '0012',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN first_response_due_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN resolution_due_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN first_response_breached_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN resolution_breached_at TEXT;

      CREATE INDEX ticket0_conversations_first_response_running ON ticket0_conversations (first_response_breached_at, first_response_due_at, id)
        WHERE first_response_due_at IS NOT NULL AND first_response_breached_at IS NULL AND first_public_reply_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL;

      CREATE INDEX ticket0_conversations_resolution_running ON ticket0_conversations (resolution_breached_at, resolution_due_at, id)
        WHERE resolution_due_at IS NOT NULL AND resolution_breached_at IS NULL AND resolved_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL;
    `,
  },
  {
    // add-ticket0_saved_replies-actions
    version: '0013',
    sql: `
      ALTER TABLE ticket0_saved_replies ADD COLUMN actions TEXT;
    `,
  },
  {
    // add-ticket0_conversations-snoozed_at-and-1-more
    version: '0014',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN snoozed_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN snoozed_ms INTEGER;

      DROP INDEX ticket0_conversations_resolution_running;

      CREATE INDEX ticket0_conversations_resolution_running ON ticket0_conversations (resolution_breached_at, resolution_due_at, id)
        WHERE resolution_due_at IS NOT NULL AND resolution_breached_at IS NULL AND resolved_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL AND snoozed_at IS NULL;
    `,
  },
  {
    // index-reaper-and-assistant-health
    version: '0015',
    sql: `
      CREATE INDEX ticket0_ai_turns_conversation_outcome ON ticket0_ai_turns (conversation_id, outcome);

      CREATE INDEX ticket0_ai_turns_created_outcome ON ticket0_ai_turns (created_at, outcome);

      CREATE INDEX ticket0_ai_turns_outcome_created ON ticket0_ai_turns (outcome, created_at, id);

      CREATE INDEX ticket0_messages_desk_reply ON ticket0_messages (conversation_id, created_at)
        WHERE visibility = 'public' AND author_kind != 'contact';
    `,
  },
  {
    // add-ticket0_agent_profiles-offboarded_at-and-3-more
    version: '0016',
    sql: `
      ALTER TABLE ticket0_agent_profiles ADD COLUMN offboarded_at TEXT;

      CREATE TABLE ticket0_behaviour_runs (
        behaviour TEXT PRIMARY KEY NOT NULL,
        last_fired_at TEXT NOT NULL,
        last_count INTEGER NOT NULL
      );

      ALTER TABLE ticket0_conversations ADD COLUMN auto_tagged_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN no_reply_notified_at TEXT;

      CREATE INDEX ticket0_conversations_untagged ON ticket0_conversations (auto_tagged_at, created_at, id)
        WHERE auto_tagged_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL;
    `,
  },
  {
    // add-ticket0_conversations-no_reply_waiting_since-and-2-more
    version: '0017',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN no_reply_waiting_since TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN no_reply_candidate_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN no_reply_notified_message_id TEXT;

      -- Populate the candidate once for live backlog from the oldest unanswered public message.
      -- Previously announced preview rows stay disarmed; future message writes re-arm them.
      UPDATE ticket0_conversations AS c
         SET no_reply_waiting_since = (
           SELECT q.created_at FROM ticket0_messages q
            WHERE q.conversation_id = c.id AND q.visibility = 'public'
              AND q.id > COALESCE((
                SELECT a.id FROM ticket0_messages a
                 WHERE a.conversation_id = c.id AND a.visibility = 'public'
                   AND (a.author_kind IN ('agent', 'assistant')
                        OR (a.author_kind = 'system' AND a.body_text != 'Passing this to a person now — someone from the team will reply here.'))
                 ORDER BY a.id DESC LIMIT 1), '')
            ORDER BY q.id LIMIT 1)
       WHERE c.state IN ('new', 'open') AND c.merged_into IS NULL;

      UPDATE ticket0_conversations
         SET no_reply_candidate_at = no_reply_waiting_since
       WHERE no_reply_waiting_since IS NOT NULL AND no_reply_notified_at IS NULL;

      CREATE INDEX ticket0_conversations_no_reply_candidate
        ON ticket0_conversations (no_reply_candidate_at, id)
        WHERE no_reply_candidate_at IS NOT NULL AND state IN ('new', 'open') AND merged_into IS NULL;
    `,
  },
  {
    // backfill-snoozed-no-reply-candidates
    version: '0018',
    sql: `
      -- 0017 already ran on PR previews; fill the snoozed backlog when they upgrade.
      -- The candidate index still excludes snoozed rows until wake-snoozed opens them.
      UPDATE ticket0_conversations AS c
         SET no_reply_waiting_since = (
           SELECT q.created_at FROM ticket0_messages q
            WHERE q.conversation_id = c.id AND q.visibility = 'public'
              AND q.id > COALESCE((
                SELECT a.id FROM ticket0_messages a
                 WHERE a.conversation_id = c.id AND a.visibility = 'public'
                   AND (a.author_kind IN ('agent', 'assistant')
                        OR (a.author_kind = 'system' AND a.body_text != 'Passing this to a person now — someone from the team will reply here.'))
                 ORDER BY a.id DESC LIMIT 1), '')
            ORDER BY q.id LIMIT 1)
       WHERE c.state = 'snoozed' AND c.merged_into IS NULL AND c.no_reply_waiting_since IS NULL;

      UPDATE ticket0_conversations
         SET no_reply_candidate_at = no_reply_waiting_since
       WHERE state = 'snoozed' AND merged_into IS NULL
         AND no_reply_waiting_since IS NOT NULL AND no_reply_candidate_at IS NULL
         AND no_reply_notified_at IS NULL;
    `,
  },
  {
    // add-ticket0_conversation_follows
    version: '0019',
    sql: `
      CREATE TABLE ticket0_conversation_follows (
        principal TEXT NOT NULL,
        conversation_id TEXT NOT NULL,
        PRIMARY KEY (principal, conversation_id)
      );

      -- Existing live entity-read tuples include follows made before this ledger existed.
      -- This is a conservative backfill: an off-boarded person loses every explicit
      -- conversation:read grant, regardless of which old path wrote it.
      INSERT INTO ticket0_conversation_follows (principal, conversation_id)
      SELECT substr(subject, length('principal:') + 1),
             substr(object, length('conversation:') + 1)
        FROM _substrat_tuples
       WHERE subject LIKE 'principal:%'
         AND relation = 'granted:conversation:read'
         AND object LIKE 'conversation:%'
         AND revoked_at IS NULL;
    `,
  },
  {
    // drop-merged-conversation-follows
    version: '0020',
    sql: `
      -- Historical merges left moved rows linked to the losing conversation as well as
      -- their current one. Keep only the edge matching the row's current SQL owner.
      -- boundary-lint-allow R4 migration #1858
      UPDATE _substrat_tuples AS t
         SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
       WHERE t.relation = 'parent' AND t.revoked_at IS NULL
         AND (
           EXISTS (SELECT 1 FROM ticket0_messages m
                    WHERE t.subject = 'message:' || m.id
                      AND t.object LIKE 'conversation:%'
                      AND t.object != 'conversation:' || m.conversation_id)
           OR EXISTS (SELECT 1 FROM ticket0_ai_turns a
                       WHERE t.subject = 'aiTurn:' || a.id
                         AND t.object LIKE 'conversation:%'
                         AND t.object != 'conversation:' || a.conversation_id)
           OR EXISTS (SELECT 1 FROM ticket0_widget_sessions w
                       WHERE t.subject = 'widgetSession:' || w.id
                         AND t.object LIKE 'conversation:%'
                         AND t.object != 'conversation:' || w.conversation_id)
         );

      -- A follow on a merged loser cannot be used to read that conversation, or its
      -- moved rows. Leave staff's scope-wide role grants and survivor follows alone.
      -- boundary-lint-allow R4 migration #1858
      UPDATE _substrat_tuples
         SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
       WHERE subject LIKE 'principal:%'
         AND relation = 'granted:conversation:read'
         AND object IN (
           SELECT 'conversation:' || id FROM ticket0_conversations
            WHERE merged_into IS NOT NULL
         )
         AND revoked_at IS NULL;

      DELETE FROM ticket0_conversation_follows
       WHERE conversation_id IN (
         SELECT id FROM ticket0_conversations WHERE merged_into IS NOT NULL
       );
    `,
  },
  {
    // add-ticket0_conversations-quarantine-and-mail-deliveries
    version: '0021',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN quarantine TEXT CHECK (quarantine IN ('suspended','discarded'));

      ALTER TABLE ticket0_conversations ADD COLUMN suspended_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN suspicion TEXT;

      CREATE TABLE ticket0_mail_deliveries (
        email_message_id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL,
        message_id TEXT,
        direction TEXT NOT NULL CHECK (direction IN ('inbound','outbound')),
        recorded_at TEXT NOT NULL
      );

      -- HAND-WRITTEN below this line (#1088). The partial indexes that hold a desk's LIVE work
      -- now hold the inbox's live work only: a suspended conversation keeps state 'new', so
      -- without this term every sweep would read it, and a spam run would sit at the head of
      -- round-robin's scan on every tick. Each WHERE is the old one plus the shared predicate
      -- (inTheInbox() in spec/model.ts), so a query that states it still implies it.
      -- NULL is the inbox, so a row an older version writes lands in every one of them.

      DROP INDEX ticket0_conversations_waiting;

      CREATE INDEX ticket0_conversations_waiting ON ticket0_conversations (assignee, created_at, id)
        WHERE assignee IS NULL AND first_assigned_at IS NULL AND state IN ('new', 'open') AND merged_into IS NULL AND quarantine IS NULL;

      DROP INDEX ticket0_conversations_first_response_running;

      CREATE INDEX ticket0_conversations_first_response_running ON ticket0_conversations (first_response_breached_at, first_response_due_at, id)
        WHERE first_response_due_at IS NOT NULL AND first_response_breached_at IS NULL AND first_public_reply_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL AND quarantine IS NULL;

      DROP INDEX ticket0_conversations_resolution_running;

      CREATE INDEX ticket0_conversations_resolution_running ON ticket0_conversations (resolution_breached_at, resolution_due_at, id)
        WHERE resolution_due_at IS NOT NULL AND resolution_breached_at IS NULL AND resolved_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL AND snoozed_at IS NULL AND quarantine IS NULL;

      DROP INDEX ticket0_conversations_untagged;

      CREATE INDEX ticket0_conversations_untagged ON ticket0_conversations (auto_tagged_at, created_at, id)
        WHERE auto_tagged_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL AND quarantine IS NULL;

      DROP INDEX ticket0_conversations_no_reply_candidate;

      CREATE INDEX ticket0_conversations_no_reply_candidate
        ON ticket0_conversations (no_reply_candidate_at, id)
        WHERE no_reply_candidate_at IS NOT NULL AND state IN ('new', 'open') AND merged_into IS NULL AND quarantine IS NULL;

      -- The suspended queue itself, newest first by id. Partial, so it holds the queue and
      -- nothing else: it is empty on every desk that never switches the filter on.
      CREATE INDEX ticket0_conversations_suspended ON ticket0_conversations (id)
        WHERE quarantine = 'suspended';

      -- Every Message-ID the desk already holds, so a redelivery of mail ingested before this
      -- migration is still recognised once the dedupe reads ticket0_mail_deliveries. Inbound
      -- is the customer's, outbound is what record-delivery stamped on a sent reply. OR IGNORE,
      -- oldest message first, so an id two messages share keeps the one that took it first.
      INSERT OR IGNORE INTO ticket0_mail_deliveries (email_message_id, conversation_id, message_id, direction, recorded_at)
        SELECT email_message_id, conversation_id, id,
               CASE WHEN author_kind = 'contact' THEN 'inbound' ELSE 'outbound' END, created_at
          FROM ticket0_messages
         WHERE email_message_id IS NOT NULL
         ORDER BY id;
    `,
  },
  {
    // add-ticket0_conversation_participants-and-rebuild-ticket0_messages
    version: '0022',
    sql: `
      CREATE TABLE ticket0_conversation_participants (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        contact_id TEXT NOT NULL REFERENCES ticket0_contacts(id),
        role TEXT NOT NULL CHECK (role IN ('cc','third-party')),
        added_by TEXT,
        created_at TEXT NOT NULL,
        UNIQUE (conversation_id, contact_id)
      );

      -- HAND-WRITTEN below this line (#1086). Who a contact is on: a discard deletes a contact
      -- the junk alone brought in, and needs to ask whether any OTHER conversation names it.
      CREATE INDEX ticket0_conversation_participants_by_contact
        ON ticket0_conversation_participants (contact_id);

      -- A contact by MAILBOX: lower(email), the same comparison addressKey() makes in code. Every
      -- lookup of a person by address — the inbound sender, a CC, a forward's third party, the
      -- blocklist's contact kind — asks it, and until now each was a scan of the table.
      CREATE INDEX ticket0_contacts_by_address ON ticket0_contacts (lower(email));

      -- ticket0_messages gains a third visibility, 'forward' (the desk and one third party), and
      -- SQLite cannot widen a CHECK in place, so the table is rebuilt the long way round: create
      -- it under a new name with the new CHECK, copy, drop, rename onto the name. No foreign key
      -- REFERENCES ticket0_messages and no trigger is defined on it, so the DROP takes nothing but
      -- the table's own indexes, and every one of them is re-created after the rename.
      --
      -- Three columns arrive with it. author_contact_id is filled for every contact message that
      -- already exists: until now the conversation's own contact was the only contact who could
      -- write in it, and a merge only ever joins two conversations of one contact. So that is a
      -- fact, not a guess. third_party_contact_id and withdrawn_at start NULL everywhere: no
      -- forward exists yet.
      CREATE TABLE ticket0_messages_new (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        author_kind TEXT NOT NULL CHECK (author_kind IN ('contact','agent','assistant','system')),
        author_principal TEXT,
        visibility TEXT NOT NULL CHECK (visibility IN ('public','internal','forward')),
        body_text TEXT NOT NULL,
        body_html TEXT,
        email_message_id TEXT,
        email_in_reply_to TEXT,
        delivered_at TEXT,
        author_contact_id TEXT,
        third_party_contact_id TEXT,
        withdrawn_at TEXT,
        cited_article_ids TEXT,
        created_at TEXT NOT NULL
      );

      INSERT INTO ticket0_messages_new
        (id, conversation_id, author_kind, author_principal, visibility, body_text, body_html,
         email_message_id, email_in_reply_to, delivered_at, author_contact_id, third_party_contact_id,
         withdrawn_at, cited_article_ids, created_at)
        SELECT m.id, m.conversation_id, m.author_kind, m.author_principal, m.visibility, m.body_text,
               m.body_html, m.email_message_id, m.email_in_reply_to, m.delivered_at,
               CASE WHEN m.author_kind = 'contact'
                    THEN (SELECT c.contact_id FROM ticket0_conversations c WHERE c.id = m.conversation_id)
               END,
               NULL, NULL, m.cited_article_ids, m.created_at
          FROM ticket0_messages m;

      DROP TABLE ticket0_messages;

      ALTER TABLE ticket0_messages_new RENAME TO ticket0_messages;

      -- Everything the DROP took, exactly as it was. The two this journal declared:
      CREATE INDEX ticket0_messages_public_by_conversation ON ticket0_messages (conversation_id, visibility, id);

      CREATE INDEX ticket0_messages_desk_reply ON ticket0_messages (conversation_id, created_at)
        WHERE visibility = 'public' AND author_kind != 'contact';

      -- New with the two columns: who wrote a message, and which third party a forward was with,
      -- for the one question that has to find a contact's messages across the desk — whether a
      -- discard may delete a contact the junk alone brought in. Partial, so a desk's own messages
      -- (no author contact) and every non-forward cost the third-party index nothing.
      CREATE INDEX ticket0_messages_by_author_contact ON ticket0_messages (author_contact_id)
        WHERE author_contact_id IS NOT NULL;

      CREATE INDEX ticket0_messages_by_third_party ON ticket0_messages (third_party_contact_id)
        WHERE third_party_contact_id IS NOT NULL;

      -- And the kernel's derived list indexes for ticket0/list-messages. The kernel applies those
      -- once per declaration and records that it did, so an unchanged declaration would never put
      -- them back: re-created here under the names and columns it derived, which
      -- test/participants.test.ts holds to a fresh desk's.
      CREATE INDEX _substrat_list_substrat_run_demo_ticket0_message_created_at ON ticket0_messages (created_at, id);

      CREATE INDEX _substrat_list_substrat_run_demo_ticket0_message_author_kind_created_at ON ticket0_messages (author_kind, created_at, id);

      CREATE INDEX _substrat_list_substrat_run_demo_ticket0_message_conversation_id_created_at ON ticket0_messages (conversation_id, created_at, id);

      CREATE INDEX _substrat_list_substrat_run_demo_ticket0_message_visibility_created_at ON ticket0_messages (visibility, created_at, id);

    `,
  },
  {
    // index-desk-reads
    version: '0023',
    sql: `
      -- Hand-written (#1554): an index for each desk read the inventory found scanning, named for
      -- the read it serves. Write cost: one more B-tree per row on each table below, and nothing on a
      -- conversation's every touch: no index here holds updated_at.

      -- list-conversations' count, which every inbox load runs: the queue, the state set, and any one
      -- of channel, priority and assignee, counted from this index over the live rows alone, where
      -- it read every conversation the desk (or that channel, priority or agent) ever had.
      CREATE INDEX ticket0_conversations_queue_filters
        ON ticket0_conversations (quarantine, state, channel, priority, assignee);

      -- my-notifications: one person's notifications in id order, not the desk's walked until theirs appear.
      CREATE INDEX ticket0_notifications_by_principal ON ticket0_notifications (principal, id);

      -- Suspend (the spam filter's, at the door), discard and merge retire or move a conversation's notifications.
      CREATE INDEX ticket0_notifications_by_conversation ON ticket0_notifications (conversation_id);

      -- widget-session reads a conversation's latest session; discard and merge delete or move its sessions.
      CREATE INDEX ticket0_widget_sessions_by_conversation ON ticket0_widget_sessions (conversation_id, started_at, id);

      -- Discard and merge rewrite a conversation's delivery records.
      CREATE INDEX ticket0_mail_deliveries_by_conversation ON ticket0_mail_deliveries (conversation_id);

      -- An inbound reply finds its thread by In-Reply-To. Partial, so a widget message or a note pays nothing.
      CREATE INDEX ticket0_messages_by_email_message_id ON ticket0_messages (email_message_id)
        WHERE email_message_id IS NOT NULL;

      -- list-participants reads a conversation's followers; discard and merge drop them.
      CREATE INDEX ticket0_conversation_follows_by_conversation ON ticket0_conversation_follows (conversation_id, principal);

    `,
  },
  {
    // widget-session-public-edges
    version: '0024',
    sql: `
      -- Hand-written (#1853): a widget session's live feed walks the edges under the session, so
      -- its subtree must be exactly what widget-thread shows the visitor.
      --
      -- First, one parent per session. moveSession used to LINK a session onto a follow-up and
      -- leave it on the closed thread; 0020 cleared what merges left, not that. Keep only the edge
      -- to the session's current conversation, so a message under a session reaches no
      -- conversation it is not on.
      -- boundary-lint-allow R4 migration #1853
      UPDATE _substrat_tuples AS t
         SET revoked_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
       WHERE t.relation = 'parent' AND t.revoked_at IS NULL
         AND EXISTS (SELECT 1 FROM ticket0_widget_sessions w
                      WHERE t.subject = 'widgetSession:' || w.id
                        AND t.object LIKE 'conversation:%'
                        AND t.object != 'conversation:' || w.conversation_id);

      -- Then the edges themselves: every public message on a session's conversation, under that
      -- session. Internal notes and forwards are not public and get none. OR IGNORE, because no
      -- such edge can exist yet: the relation is new with this migration.
      -- boundary-lint-allow R4 migration #1853
      INSERT OR IGNORE INTO _substrat_tuples (subject, relation, object)
        SELECT 'message:' || m.id, 'parent', 'widgetSession:' || w.id
          FROM ticket0_widget_sessions w
          JOIN ticket0_messages m ON m.conversation_id = w.conversation_id
         WHERE m.visibility = 'public';
    `,
  },
  {
    // saved-reply-owner-folders-and-usage
    version: '0025',
    sql: `
      CREATE TABLE ticket0_saved_reply_folders (
        id TEXT PRIMARY KEY NOT NULL,
        name TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (name)
      );

      -- HAND-WRITTEN below this line (#1087). A saved reply gains an owner (personal or the
      -- desk's), a folder, and a usage count, and its title becomes unique per OWNER rather than
      -- across the desk. SQLite cannot change a UNIQUE constraint in place, so the table is
      -- rebuilt the long way round: create it under a new name, copy, drop, rename onto the name.
      -- No foreign key REFERENCES ticket0_saved_replies and no trigger is defined on it, and its
      -- only indexes were the old UNIQUE (title) and the kernel's derived list indexes for the
      -- old list-saved-replies declaration, which no longer exists: the list is composed by its
      -- handler now, so there is nothing to re-create.
      --
      -- owner is '' for the desk's own, shared reply, and every reply that exists today is one:
      -- before this, there was no other kind. '' rather than NULL so UNIQUE (owner, title) holds
      -- for shared replies too: SQLite treats every NULL as distinct. Every row starts unfiled and
      -- at a count of 0, because nothing before this recorded a use. The old UNIQUE (title) means
      -- the copy cannot collide under the new key.
      CREATE TABLE ticket0_saved_replies_new (
        id TEXT PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        owner TEXT NOT NULL DEFAULT '',
        folder_id TEXT,
        use_count INTEGER NOT NULL DEFAULT 0,
        last_used_at TEXT,
        actions TEXT,
        UNIQUE (owner, title)
      );

      INSERT INTO ticket0_saved_replies_new
        (id, title, body, created_by, created_at, owner, folder_id, use_count, last_used_at, actions)
        SELECT id, title, body, created_by, created_at, '', NULL, 0, NULL, actions
          FROM ticket0_saved_replies;

      DROP TABLE ticket0_saved_replies;

      ALTER TABLE ticket0_saved_replies_new RENAME TO ticket0_saved_replies;
    `,
  },
];
