/**
 * GENERATED by tools/emit-migrations.mts from journal.json — do not edit by hand.
 *
 * The journal is the record; this is the shape the kernel registers. Append a
 * migration by changing spec/model.ts and re-running:
 *
 *     pnpm --filter @substrat-run/demo-ticket0 emit:migrations
 *
 * CI re-emits with --check and fails on drift, so a hand-edit to shipped SQL is
 * caught here rather than at the next deploy.
 */
import type { SqlMigration } from '@substrat-run/kernel';

export const ticket0Migrations: SqlMigration[] = [
  {
    // add-ticket0_agent_profiles-and-13-more
    version: '0001',
    sql: `
      CREATE TABLE ticket0_agent_profiles (
        principal TEXT PRIMARY KEY NOT NULL,
        display_name TEXT NOT NULL,
        avatar_url TEXT,
        signature TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_ai_turns (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        message_id TEXT,
        model TEXT NOT NULL,
        input_tokens INTEGER NOT NULL,
        output_tokens INTEGER NOT NULL,
        cited_article_ids TEXT NOT NULL,
        confidence INTEGER,
        outcome TEXT NOT NULL CHECK (outcome IN ('drafted','answered','escalated','failed')),
        meter_entry_id TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_contacts (
        id TEXT PRIMARY KEY NOT NULL,
        external_id TEXT,
        principal TEXT,
        email TEXT,
        display_name TEXT,
        verified_at TEXT,
        created_at TEXT NOT NULL,
        UNIQUE (external_id)
      );

      CREATE TABLE ticket0_conversation_tags (
        conversation_id TEXT NOT NULL,
        tag TEXT NOT NULL,
        created_at TEXT NOT NULL,
        PRIMARY KEY (conversation_id, tag)
      );

      CREATE TABLE ticket0_conversations (
        id TEXT PRIMARY KEY NOT NULL,
        contact_id TEXT NOT NULL REFERENCES ticket0_contacts(id),
        channel TEXT NOT NULL CHECK (channel IN ('widget','email')),
        subject TEXT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('new','open','snoozed','resolved','closed')),
        assignee TEXT,
        priority TEXT NOT NULL CHECK (priority IN ('low','normal','urgent')),
        snoozed_until TEXT,
        first_public_reply_at TEXT,
        resolved_at TEXT,
        merged_into TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_csat (
        conversation_id TEXT PRIMARY KEY NOT NULL,
        score INTEGER NOT NULL,
        comment TEXT,
        submitted_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_desk_settings (
        id TEXT PRIMARY KEY NOT NULL,
        from_address TEXT NOT NULL,
        greeting TEXT NOT NULL,
        allowed_origins TEXT NOT NULL,
        verification_secret TEXT NOT NULL,
        business_hours TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_kb_articles (
        id TEXT PRIMARY KEY NOT NULL,
        source_id TEXT NOT NULL,
        url TEXT NOT NULL,
        title TEXT NOT NULL,
        heading_path TEXT NOT NULL,
        body TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        ingested_at TEXT NOT NULL,
        UNIQUE (source_id, url)
      );

      CREATE TABLE ticket0_kb_sources (
        id TEXT PRIMARY KEY NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('llms-txt','sitemap','markdown')),
        url TEXT NOT NULL,
        label TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('idle','ingesting','failed')),
        last_ingested_at TEXT,
        last_error TEXT,
        created_at TEXT NOT NULL,
        UNIQUE (url)
      );

      CREATE TABLE ticket0_messages (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        author_kind TEXT NOT NULL CHECK (author_kind IN ('contact','agent','assistant','system')),
        author_principal TEXT,
        visibility TEXT NOT NULL CHECK (visibility IN ('public','internal')),
        body_text TEXT NOT NULL,
        body_html TEXT,
        email_message_id TEXT,
        email_in_reply_to TEXT,
        delivered_at TEXT,
        cited_article_ids TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_notifications (
        id TEXT PRIMARY KEY NOT NULL,
        principal TEXT NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('assigned','replied','mentioned','snooze-woke','escalated')),
        conversation_id TEXT,
        read_at TEXT,
        created_at TEXT NOT NULL
      );

      CREATE TABLE ticket0_saved_replies (
        id TEXT PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (title)
      );

      CREATE TABLE ticket0_usage_rates (
        meter_key TEXT NOT NULL,
        unit_price TEXT NOT NULL,
        currency TEXT NOT NULL,
        effective_from TEXT NOT NULL,
        PRIMARY KEY (meter_key, effective_from)
      );

      CREATE TABLE ticket0_widget_sessions (
        id TEXT PRIMARY KEY NOT NULL,
        conversation_id TEXT NOT NULL REFERENCES ticket0_conversations(id),
        contact_id TEXT NOT NULL,
        origin TEXT NOT NULL,
        token_hash TEXT NOT NULL,
        started_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL,
        UNIQUE (token_hash)
      );
    `,
  },
  {
    // add-ticket0_widget_openings
    version: '0002',
    sql: `
      CREATE TABLE ticket0_widget_openings (
        id TEXT PRIMARY KEY NOT NULL,
        contact_id TEXT,
        origin TEXT NOT NULL,
        token_hash TEXT NOT NULL,
        started_at TEXT NOT NULL,
        last_seen_at TEXT NOT NULL,
        UNIQUE (token_hash)
      );
    `,
  },
  {
    // add-ticket0_widget_openings-user_agent-and-21-more
    version: '0003',
    sql: `
      ALTER TABLE ticket0_widget_openings ADD COLUMN user_agent TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN language TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN browser TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN browser_version TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN os TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN os_version TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN device TEXT CHECK (device IN ('desktop','mobile','tablet','bot','unknown'));

      ALTER TABLE ticket0_widget_openings ADD COLUMN country TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN region TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN city TEXT;

      ALTER TABLE ticket0_widget_openings ADD COLUMN timezone TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN user_agent TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN language TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN browser TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN browser_version TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN os TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN os_version TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN device TEXT CHECK (device IN ('desktop','mobile','tablet','bot','unknown'));

      ALTER TABLE ticket0_widget_sessions ADD COLUMN country TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN region TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN city TEXT;

      ALTER TABLE ticket0_widget_sessions ADD COLUMN timezone TEXT;
    `,
  },
  {
    // add-ticket0_ai_turns-error
    version: '0004',
    sql: `
      ALTER TABLE ticket0_ai_turns ADD COLUMN error TEXT;
    `,
  },
  {
    // add-ticket0_desk_settings-assistant_autonomous
    version: '0005',
    sql: `
      ALTER TABLE ticket0_desk_settings ADD COLUMN assistant_autonomous INTEGER;
    `,
  },
  {
    // add-ticket0_signups
    version: '0006',
    sql: `
      CREATE TABLE ticket0_signups (
        id TEXT PRIMARY KEY NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('waitlist','newsletter')),
        email TEXT NOT NULL,
        note TEXT,
        state TEXT NOT NULL CHECK (state IN ('pending','confirmed','unsubscribed')),
        origin TEXT NOT NULL,
        confirm_token_hash TEXT,
        unsubscribe_token TEXT NOT NULL,
        requested_at TEXT NOT NULL,
        confirmed_at TEXT,
        unsubscribed_at TEXT,
        created_at TEXT NOT NULL,
        UNIQUE (kind, email)
      );
    `,
  },
  {
    // add-ticket0_conversations-follows
    version: '0007',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN follows TEXT;
    `,
  },
  {
    // add-ticket0_kb_sources-refresh_token_hash-and-3-more
    version: '0008',
    sql: `
      ALTER TABLE ticket0_kb_sources ADD COLUMN refresh_token_hash TEXT;

      ALTER TABLE ticket0_kb_sources ADD COLUMN refresh_token_hint TEXT;

      ALTER TABLE ticket0_kb_sources ADD COLUMN token_created_at TEXT;

      ALTER TABLE ticket0_kb_sources ADD COLUMN token_last_used_at TEXT;
    `,
  },
  {
    // add-ticket0_desk_settings-abandoned_after_days
    version: '0009',
    sql: `
      ALTER TABLE ticket0_desk_settings ADD COLUMN abandoned_after_days INTEGER;
    `,
  },
  {
    // add-ticket0_block_rules
    version: '0010',
    sql: `
      CREATE TABLE ticket0_block_rules (
        id TEXT PRIMARY KEY NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('email','domain','contact')),
        value TEXT NOT NULL,
        reason TEXT,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (kind, value)
      );
    `,
  },
  {
    // add-ticket0_conversations-first_assigned_at-and-2-more
    version: '0011',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN first_assigned_at TEXT;

      ALTER TABLE ticket0_desk_settings ADD COLUMN settings TEXT;

      ALTER TABLE ticket0_desk_settings ADD COLUMN round_robin_last TEXT;

      CREATE INDEX ticket0_conversations_waiting ON ticket0_conversations (assignee, created_at, id)
        WHERE assignee IS NULL AND first_assigned_at IS NULL AND state IN ('new', 'open') AND merged_into IS NULL;

      CREATE INDEX ticket0_ai_turns_by_conversation ON ticket0_ai_turns (conversation_id, created_at, id);

      CREATE INDEX ticket0_messages_public_by_conversation ON ticket0_messages (conversation_id, visibility, id);
    `,
  },
  {
    // add-ticket0_conversations-first_response_due_at-and-3-more
    version: '0012',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN first_response_due_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN resolution_due_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN first_response_breached_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN resolution_breached_at TEXT;

      CREATE INDEX ticket0_conversations_first_response_running ON ticket0_conversations (first_response_breached_at, first_response_due_at, id)
        WHERE first_response_due_at IS NOT NULL AND first_response_breached_at IS NULL AND first_public_reply_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL;

      CREATE INDEX ticket0_conversations_resolution_running ON ticket0_conversations (resolution_breached_at, resolution_due_at, id)
        WHERE resolution_due_at IS NOT NULL AND resolution_breached_at IS NULL AND resolved_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL;
    `,
  },
  {
    // add-ticket0_saved_replies-actions
    version: '0013',
    sql: `
      ALTER TABLE ticket0_saved_replies ADD COLUMN actions TEXT;
    `,
  },
  {
    // add-ticket0_conversations-snoozed_at-and-1-more
    version: '0014',
    sql: `
      ALTER TABLE ticket0_conversations ADD COLUMN snoozed_at TEXT;

      ALTER TABLE ticket0_conversations ADD COLUMN snoozed_ms INTEGER;

      DROP INDEX ticket0_conversations_resolution_running;

      CREATE INDEX ticket0_conversations_resolution_running ON ticket0_conversations (resolution_breached_at, resolution_due_at, id)
        WHERE resolution_due_at IS NOT NULL AND resolution_breached_at IS NULL AND resolved_at IS NULL AND state IN ('new', 'open', 'snoozed') AND merged_into IS NULL AND snoozed_at IS NULL;
    `,
  },
  {
    // index-reaper-and-assistant-health
    version: '0015',
    sql: `
      CREATE INDEX ticket0_ai_turns_conversation_outcome ON ticket0_ai_turns (conversation_id, outcome);

      CREATE INDEX ticket0_ai_turns_created_outcome ON ticket0_ai_turns (created_at, outcome);

      CREATE INDEX ticket0_ai_turns_outcome_created ON ticket0_ai_turns (outcome, created_at, id);

      CREATE INDEX ticket0_messages_desk_reply ON ticket0_messages (conversation_id, created_at)
        WHERE visibility = 'public' AND author_kind != 'contact';
    `,
  },
];
