/**
 * GENERATED by scripts/gen-schema.mts from Better Auth's own table declarations
 * (`getAuthTables` over the real `buildAuth` config) — do not edit by hand.
 * Re-emit with `pnpm --filter @substrat-run/demo-auth-server gen:schema`;
 * `test/schema-generated.test.ts` fails if this file and the config disagree.
 *
 * The Drizzle schema the Better Auth adapter reads. Column names are snake_case — this file
 * is what maps Better Auth's camelCase fields onto them, so the adapter and `db/ddl.generated.ts`
 * cannot disagree about a name.
 *
 * SQLite is not a `supportsJSON`/`supportsArrays` provider for the drizzle adapter, so
 * `string[]` and `json` fields arrive already serialized and their columns are plain `text` —
 * declaring `mode: 'json'` here would round-trip every value through JSON twice.
 */
import { sql } from 'drizzle-orm';
import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

/** SQLite's own clock, in the epoch-ms Better Auth stores dates as. */
const nowMs = sql`(cast(unixepoch('subsecond') * 1000 as integer))`;

export const user = sqliteTable(
  'user',
  {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  email: text('email').unique().notNull(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(),
  image: text('image'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
  role: text('role'),
  banned: integer('banned', { mode: 'boolean' }).default(false),
  banReason: text('ban_reason'),
  banExpires: integer('ban_expires', { mode: 'timestamp_ms' }),
  },
);

export const session = sqliteTable(
  'session',
  {
  id: text('id').primaryKey().notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  token: text('token').unique().notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }).notNull(),
  impersonatedBy: text('impersonated_by'),
  },
  (table) => [index('session_user_id_idx').on(table.userId)],
);

export const account = sqliteTable(
  'account',
  {
  id: text('id').primaryKey().notNull(),
  issuer: text('issuer').notNull(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }).notNull(),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
  refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [index('account_user_id_idx').on(table.userId), uniqueIndex('account_issuer_account_id_idx').on(table.issuer, table.accountId)],
);

export const verification = sqliteTable(
  'verification',
  {
  id: text('id').primaryKey().notNull(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).default(nowMs).notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
);

export const jwks = sqliteTable(
  'jwks',
  {
  id: text('id').primaryKey().notNull(),
  publicKey: text('public_key').notNull(),
  privateKey: text('private_key').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }),
  alg: text('alg'),
  crv: text('crv'),
  },
);

export const oauthClient = sqliteTable(
  'oauth_client',
  {
  id: text('id').primaryKey().notNull(),
  clientId: text('client_id').unique().notNull(),
  clientSecret: text('client_secret'),
  clientDiscoveryId: text('client_discovery_id'),
  disabled: integer('disabled', { mode: 'boolean' }).default(false),
  skipConsent: integer('skip_consent', { mode: 'boolean' }),
  enableEndSession: integer('enable_end_session', { mode: 'boolean' }),
  subjectType: text('subject_type'),
  scopes: text('scopes'),
  clientCredentialsScopes: text('client_credentials_scopes').default('[]'),
  userId: text('user_id').references(() => user.id),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }),
  name: text('name'),
  uri: text('uri'),
  icon: text('icon'),
  contacts: text('contacts'),
  tos: text('tos'),
  policy: text('policy'),
  softwareId: text('software_id'),
  softwareVersion: text('software_version'),
  softwareStatement: text('software_statement'),
  redirectUris: text('redirect_uris').notNull(),
  postLogoutRedirectUris: text('post_logout_redirect_uris'),
  backchannelLogoutUri: text('backchannel_logout_uri'),
  backchannelLogoutSessionRequired: integer('backchannel_logout_session_required', { mode: 'boolean' }),
  tokenEndpointAuthMethod: text('token_endpoint_auth_method'),
  applicationType: text('application_type'),
  jwks: text('jwks'),
  jwksUri: text('jwks_uri'),
  grantTypes: text('grant_types'),
  responseTypes: text('response_types'),
  requirePKCE: integer('require_p_k_c_e', { mode: 'boolean' }),
  dpopBoundAccessTokens: integer('dpop_bound_access_tokens', { mode: 'boolean' }).default(false),
  referenceId: text('reference_id'),
  metadata: text('metadata'),
  },
  (table) => [index('oauth_client_user_id_idx').on(table.userId)],
);

export const oauthResource = sqliteTable(
  'oauth_resource',
  {
  id: text('id').primaryKey().notNull(),
  identifier: text('identifier').unique().notNull(),
  name: text('name').notNull(),
  accessTokenTtl: integer('access_token_ttl'),
  refreshTokenTtl: integer('refresh_token_ttl'),
  signingAlgorithm: text('signing_algorithm'),
  signingKeyId: text('signing_key_id'),
  allowedScopes: text('allowed_scopes'),
  customClaims: text('custom_claims'),
  dpopBoundAccessTokensRequired: integer('dpop_bound_access_tokens_required', { mode: 'boolean' }).default(false),
  disabled: integer('disabled', { mode: 'boolean' }).default(false),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }),
  policyVersion: integer('policy_version').default(1),
  metadata: text('metadata'),
  },
);

export const oauthClientResource = sqliteTable(
  'oauth_client_resource',
  {
  id: text('id').primaryKey().notNull(),
  clientId: text('client_id').references(() => oauthClient.clientId, { onDelete: 'cascade' }).notNull(),
  resourceId: text('resource_id').references(() => oauthResource.identifier, { onDelete: 'cascade' }).notNull(),
  metadata: text('metadata'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }),
  },
  (table) => [index('oauth_client_resource_client_id_idx').on(table.clientId), index('oauth_client_resource_resource_id_idx').on(table.resourceId), uniqueIndex('oauth_client_resource_client_id_resource_id_idx').on(table.clientId, table.resourceId)],
);

export const oauthRefreshToken = sqliteTable(
  'oauth_refresh_token',
  {
  id: text('id').primaryKey().notNull(),
  token: text('token').unique().notNull(),
  clientId: text('client_id').references(() => oauthClient.clientId).notNull(),
  sessionId: text('session_id').references(() => session.id, { onDelete: 'set null' }),
  userId: text('user_id').references(() => user.id).notNull(),
  referenceId: text('reference_id'),
  authorizationCodeId: text('authorization_code_id'),
  resources: text('resources'),
  requestedUserInfoClaims: text('requested_user_info_claims'),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  revoked: integer('revoked', { mode: 'timestamp_ms' }),
  rotatedAt: integer('rotated_at', { mode: 'timestamp_ms' }),
  rotationReplayResponse: text('rotation_replay_response'),
  rotationReplayExpiresAt: integer('rotation_replay_expires_at', { mode: 'timestamp_ms' }),
  authTime: integer('auth_time', { mode: 'timestamp_ms' }),
  confirmation: text('confirmation'),
  scopes: text('scopes').notNull(),
  },
  (table) => [index('oauth_refresh_token_client_id_idx').on(table.clientId), index('oauth_refresh_token_session_id_idx').on(table.sessionId), index('oauth_refresh_token_user_id_idx').on(table.userId), index('oauth_refresh_token_authorization_code_id_idx').on(table.authorizationCodeId)],
);

export const oauthAccessToken = sqliteTable(
  'oauth_access_token',
  {
  id: text('id').primaryKey().notNull(),
  token: text('token').unique().notNull(),
  clientId: text('client_id').references(() => oauthClient.clientId).notNull(),
  sessionId: text('session_id').references(() => session.id, { onDelete: 'set null' }),
  userId: text('user_id').references(() => user.id),
  referenceId: text('reference_id'),
  authorizationCodeId: text('authorization_code_id'),
  resources: text('resources'),
  requestedUserInfoClaims: text('requested_user_info_claims'),
  refreshId: text('refresh_id').references(() => oauthRefreshToken.id),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  revoked: integer('revoked', { mode: 'timestamp_ms' }),
  confirmation: text('confirmation'),
  scopes: text('scopes').notNull(),
  },
  (table) => [index('oauth_access_token_client_id_idx').on(table.clientId), index('oauth_access_token_session_id_idx').on(table.sessionId), index('oauth_access_token_user_id_idx').on(table.userId), index('oauth_access_token_authorization_code_id_idx').on(table.authorizationCodeId), index('oauth_access_token_refresh_id_idx').on(table.refreshId)],
);

export const oauthConsent = sqliteTable(
  'oauth_consent',
  {
  id: text('id').primaryKey().notNull(),
  clientId: text('client_id').references(() => oauthClient.clientId).notNull(),
  userId: text('user_id').references(() => user.id),
  referenceId: text('reference_id'),
  resources: text('resources'),
  requestedUserInfoClaims: text('requested_user_info_claims'),
  scopes: text('scopes').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [index('oauth_consent_client_id_idx').on(table.clientId), index('oauth_consent_user_id_idx').on(table.userId)],
);

export const oauthClientAssertion = sqliteTable(
  'oauth_client_assertion',
  {
  id: text('id').primaryKey().notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  },
);

export const schema = {
  user,
  session,
  account,
  verification,
  jwks,
  oauthClient,
  oauthResource,
  oauthClientResource,
  oauthRefreshToken,
  oauthAccessToken,
  oauthConsent,
  oauthClientAssertion,
};
