// GENERATED by tools/client-emit.mts from spec/model.ts — do not edit by hand.
//
// Re-emit with `pnpm lint:client`; CI runs `pnpm lint:client --check` and fails on
// drift, so the client cannot fall behind the model the way a hand-written one did.
//
// Standalone on purpose: no imports, so the browser bundle carries no schema library
// and `tools/declared-deps.mjs` has nothing to object to.

/** A failed request. `status` is the interesting field — 403 is the permission model answering. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
    readonly body: unknown,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

/**
 * One page of a paged read, reassembled from the response.
 *
 * The BODY is the entries and always was; the walk rides in headers (#829), which is
 * what let paging be adopted without renaming a live endpoint's response. This puts
 * the two back together so a caller sees a page rather than a header protocol.
 *
 * `next` is an absolute URL to FOLLOW (RFC 8288), not a cursor to reassemble — this
 * request's filters and page size travel with it. Its absence is how the walk ends.
 */
export interface Paged<T> {
  entries: T[];
  /** Hand back to `follow()`. `null` when there is no next page. */
  next: string | null;
  /** From `X-Total-Count`, and only for a read that declares `total`. */
  total: number | null;
}

export interface ClientOptions {
  /** Prefixed to every declared path. Matches `mountOperations`' own default. */
  baseUrl?: string;
  /** Per-request headers — an auth token, or this demo's `x-principal` persona seam. */
  headers?: () => Record<string, string>;
  /** Injectable so the client works under a test harness, not only in a browser. */
  fetch?: typeof globalThis.fetch;
  /**
   * Pull a message out of an error body.
   *
   * The one thing here the model does NOT declare: a vertical picks its error
   * envelope in its own `app.onError`, so this is a best effort over the shapes in
   * use — `{ error }`, and problem+json's `detail`/`title` — and an app that
   * answers something else says so here rather than being guessed at.
   */
  errorMessage?: (body: unknown, response: Response) => string | undefined;
}

function defaultErrorMessage(body: unknown): string | undefined {
  if (typeof body !== 'object' || body === null) return undefined;
  const b = body as Record<string, unknown>;
  for (const key of ['error', 'detail', 'title', 'message']) {
    if (typeof b[key] === 'string') return b[key] as string;
  }
  return undefined;
}


/** `ticket0_contacts` — declared in spec/model.ts. */
export interface Contact {
  id: string;
  external_id: string | null;
  principal: string | null;
  email: string | null;
  display_name: string | null;
  verified_at: string | null;
  created_at: string;
}

/** `ticket0_agent_profiles` — declared in spec/model.ts. */
export interface AgentProfile {
  principal: string;
  display_name: string;
  avatar_url: string | null;
  signature: string | null;
  created_at: string;
}

/** `ticket0_conversations` — declared in spec/model.ts. */
export interface Conversation {
  id: string;
  contact_id: string;
  channel: "widget" | "email";
  subject: string;
  state: "new" | "open" | "snoozed" | "resolved" | "closed";
  assignee: string | null;
  priority: "low" | "normal" | "urgent";
  snoozed_until: string | null;
  first_public_reply_at: string | null;
  resolved_at: string | null;
  merged_into: string | null;
  created_at: string;
  updated_at: string;
}

/** `ticket0_messages` — declared in spec/model.ts. */
export interface Message {
  id: string;
  conversation_id: string;
  author_kind: "contact" | "agent" | "assistant" | "system";
  author_principal: string | null;
  visibility: "public" | "internal";
  body_text: string;
  body_html: string | null;
  email_message_id: string | null;
  email_in_reply_to: string | null;
  delivered_at: string | null;
  cited_article_ids: string | null;
  created_at: string;
}

/** `ticket0_conversation_tags` — declared in spec/model.ts. */
export interface ConversationTag {
  conversation_id: string;
  tag: string;
  created_at: string;
}

/** `ticket0_saved_replies` — declared in spec/model.ts. */
export interface SavedReply {
  id: string;
  title: string;
  body: string;
  created_by: string;
  created_at: string;
}

/** `ticket0_csat` — declared in spec/model.ts. */
export interface Csat {
  conversation_id: string;
  score: number;
  comment: string | null;
  submitted_at: string;
}

/** `ticket0_widget_sessions` — declared in spec/model.ts. */
export interface WidgetSession {
  id: string;
  conversation_id: string;
  contact_id: string;
  origin: string;
  token_hash: string;
  started_at: string;
  last_seen_at: string;
  user_agent: string | null;
  language: string | null;
  browser: string | null;
  browser_version: string | null;
  os: string | null;
  os_version: string | null;
  device: "desktop" | "mobile" | "tablet" | "bot" | "unknown" | null;
  country: string | null;
  region: string | null;
  city: string | null;
  timezone: string | null;
}

/** `ticket0_widget_openings` — declared in spec/model.ts. */
export interface WidgetOpening {
  id: string;
  contact_id: string | null;
  origin: string;
  token_hash: string;
  started_at: string;
  last_seen_at: string;
  user_agent: string | null;
  language: string | null;
  browser: string | null;
  browser_version: string | null;
  os: string | null;
  os_version: string | null;
  device: "desktop" | "mobile" | "tablet" | "bot" | "unknown" | null;
  country: string | null;
  region: string | null;
  city: string | null;
  timezone: string | null;
}

/** `ticket0_desk_settings` — declared in spec/model.ts. */
export interface DeskSettings {
  id: string;
  from_address: string;
  greeting: string;
  allowed_origins: string;
  verification_secret: string;
  business_hours: string | null;
  created_at: string;
  updated_at: string;
}

/** `ticket0_kb_sources` — declared in spec/model.ts. */
export interface KbSource {
  id: string;
  kind: "llms-txt" | "sitemap" | "markdown";
  url: string;
  label: string;
  status: "idle" | "ingesting" | "failed";
  last_ingested_at: string | null;
  last_error: string | null;
  created_at: string;
}

/** `ticket0_kb_articles` — declared in spec/model.ts. */
export interface KbArticle {
  id: string;
  source_id: string;
  url: string;
  title: string;
  heading_path: string;
  body: string;
  content_hash: string;
  ingested_at: string;
}

/** `ticket0_ai_turns` — declared in spec/model.ts. */
export interface AiTurn {
  id: string;
  conversation_id: string;
  message_id: string | null;
  model: string;
  input_tokens: number;
  output_tokens: number;
  cited_article_ids: string;
  confidence: number | null;
  outcome: "drafted" | "answered" | "escalated" | "failed";
  meter_entry_id: string | null;
  error: string | null;
  created_at: string;
}

/** `ticket0_usage_rates` — declared in spec/model.ts. */
export interface UsageRate {
  meter_key: string;
  unit_price: string;
  currency: string;
  effective_from: string;
}

/** `ticket0_notifications` — declared in spec/model.ts. */
export interface Notification {
  id: string;
  principal: string;
  kind: "assigned" | "replied" | "mentioned" | "snooze-woke" | "escalated";
  conversation_id: string | null;
  read_at: string | null;
  created_at: string;
}

/** Every operation this vertical binds to HTTP, one method each. */
export interface Ticket0Client {
  /**
   * Point the desk at a source of documentation
   *
   * `POST /kb/sources` — `ticket0/add-kb-source`
   */
  addKbSource(input: { kind: "llms-txt" | "sitemap" | "markdown"; url: string; label: string }): Promise<KbSource>;

  /**
   * Assign a conversation to someone (or nobody)
   *
   * `POST /conversations/{conversationId}/assignee` — `ticket0/assign`
   */
  assign(input: { conversationId: string; assignee: string | null }): Promise<Conversation>;

  /**
   * Recent assistant failures, for the admin deciding whether it is working
   *
   * `GET /assistant/health` — `ticket0/assistant-health`
   */
  assistantHealth(): Promise<{ since: string; turns: number; failed: number; recent: ({ id: string; conversation_id: string; subject: string; model: string; error: string | null; created_at: string })[] }>;

  /**
   * Close a resolved conversation for good
   *
   * `POST /conversations/{conversationId}/close` — `ticket0/close`
   */
  close(input: { conversationId: string }): Promise<Conversation>;

  /**
   * Close a billing period
   *
   * `POST /usage/periods` — `ticket0/close-usage-period`
   */
  closeUsagePeriod(input: { from: string; to: string }): Promise<{ periodId: string; from: string; to: string; lines: number }>;

  /**
   * Change the desk’s settings
   *
   * `PATCH /desk` — `ticket0/configure-desk`
   */
  configureDesk(input: { fromAddress?: string; greeting?: string; allowedOrigins?: string[]; businessHours?: string | null }): Promise<{ id: string; from_address: string; greeting: string; allowed_origins: string; business_hours: string | null; created_at: string; updated_at: string }>;

  /**
   * Save a canned answer
   *
   * `POST /saved-replies` — `ticket0/create-saved-reply`
   */
  createSavedReply(input: { title: string; body: string }): Promise<SavedReply>;

  /**
   * Delete a canned answer
   *
   * `DELETE /saved-replies/{savedReplyId}` — `ticket0/delete-saved-reply`
   *
   * Concurrency-checked over `savedReply`. The tag this answers with is
   * remembered and sent as `If-Match` on the next write to the same entity, so a
   * write that would overwrite someone else's change fails with 412 instead.
   */
  deleteSavedReply(input: { savedReplyId: string }): Promise<{ id: string; title: string }>;

  /**
   * Volume, speed, backlog, satisfaction and what the assistant settled
   *
   * `GET /desk-metrics` — `ticket0/desk-metrics`
   */
  deskMetrics(input: { from?: string; to?: string }): Promise<{ from: string; to: string; volume: { opened: number; resolved: number; byChannel: ({ channel: "widget" | "email"; opened: number; resolved: number })[] }; firstResponse: { measured: number; medianSeconds: number | null; p90Seconds: number | null }; resolution: { measured: number; medianSeconds: number | null; p90Seconds: number | null }; backlog: { open: number; snoozed: number; unassigned: number; oldestUntouchedId: string | null; oldestUntouchedAgeSeconds: number | null }; agents: ({ principal: string; displayName: string | null; resolved: number; replies: number })[]; csat: { responses: number; average: number | null }; assistant: { turns: number; answered: number; drafted: number; escalated: number; failed: number; deflectionRate: number | null; escalationRate: number | null; failureRate: number | null; currency: string; cost: string; costPerResolved: string | null } }>;

  /**
   * One conversation
   *
   * `GET /conversations/{conversationId}` — `ticket0/get-conversation`
   */
  getConversation(input: { conversationId: string }): Promise<Conversation>;

  /**
   * The satisfaction rating on a conversation, if there is one
   *
   * `GET /conversations/{conversationId}/csat` — `ticket0/get-csat`
   */
  getCsat(input: { conversationId: string }): Promise<{ csat: Csat | null }>;

  /**
   * The desk’s settings
   *
   * `GET /desk` — `ticket0/get-desk`
   */
  getDesk(): Promise<{ id: string; from_address: string; greeting: string; allowed_origins: string; business_hours: string | null; created_at: string; updated_at: string }>;

  /**
   * One canned answer
   *
   * `GET /saved-replies/{savedReplyId}` — `ticket0/get-saved-reply`
   *
   * Concurrency-checked over `savedReply`. The tag this answers with is
   * remembered and sent as `If-Match` on the next write to the same entity, so a
   * write that would overwrite someone else's change fails with 412 instead.
   */
  getSavedReply(input: { savedReplyId: string }): Promise<SavedReply>;

  /**
   * Re-read a documentation source
   *
   * `POST /kb/sources/{sourceId}/ingest` — `ticket0/ingest-kb-source`
   */
  ingestKbSource(input: { sourceId: string }): Promise<KbSource>;

  /**
   * Record a message that arrived from outside
   *
   * `POST /relay/inbound` — `ticket0/ingest-message`
   */
  ingestMessage(input: { conversationId: string | null; contactEmail: string; contactName?: string | null; subject: string; bodyText: string; bodyHtml?: string | null; emailMessageId: string; emailInReplyTo?: string | null }): Promise<Message>;

  /**
   * The staff of this desk
   *
   * `GET /agents` — `ticket0/list-agents`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listAgents(): Promise<Paged<AgentProfile>>;

  /**
   * The people who have asked something
   *
   * `GET /contacts` — `ticket0/list-contacts`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listContacts(): Promise<Paged<Contact>>;

  /**
   * The tags on a conversation
   *
   * `GET /conversations/{conversationId}/tags` — `ticket0/list-conversation-tags`
   */
  listConversationTags(input: { conversationId: string }): Promise<{ tags: ConversationTag[] }>;

  /**
   * The desk’s conversations
   *
   * `GET /conversations` — `ticket0/list-conversations`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listConversations(input: { state?: "new" | "open" | "snoozed" | "resolved" | "closed"; assignee?: string; channel?: "widget" | "email"; priority?: "low" | "normal" | "urgent"; contact_id?: string }): Promise<Paged<Conversation>>;

  /**
   * The desk’s documentation sources
   *
   * `GET /kb/sources` — `ticket0/list-kb-sources`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listKbSources(): Promise<Paged<KbSource>>;

  /**
   * Every message on a conversation, notes included
   *
   * `GET /conversations/{conversationId}/messages` — `ticket0/list-messages`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listMessages(input: { conversationId: string }): Promise<Paged<({ id: string; conversation_id: string; author_kind: "contact" | "agent" | "assistant" | "system"; author_principal: string | null; visibility: "public" | "internal"; body_text: string; body_html: string | null; email_message_id: string | null; email_in_reply_to: string | null; delivered_at: string | null; cited_article_ids: string | null; created_at: string; citations: { id: string; title: string; url: string; headingPath: string }[] })>>;

  /**
   * The desk’s canned answers
   *
   * `GET /saved-replies` — `ticket0/list-saved-replies`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listSavedReplies(): Promise<Paged<SavedReply>>;

  /**
   * Every tag the desk uses, most-used first
   *
   * `GET /tags` — `ticket0/list-tags`
   */
  listTags(): Promise<{ tags: { tag: string; count: number }[] }>;

  /**
   * What the assistant produced on this conversation
   *
   * `GET /conversations/{conversationId}/turns` — `ticket0/list-turns`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listTurns(input: { conversationId: string }): Promise<Paged<({ id: string; conversation_id: string; message_id: string | null; model: string; confidence: number | null; outcome: "drafted" | "answered" | "escalated" | "failed"; error: string | null; created_at: string; citations: { id: string; title: string; url: string; headingPath: string }[] })>>;

  /**
   * Mark a notification read
   *
   * `POST /me/notifications/{notificationId}/read` — `ticket0/mark-notification-read`
   */
  markNotificationRead(input: { notificationId: string }): Promise<Notification>;

  /**
   * Merge this conversation into another
   *
   * `POST /conversations/{conversationId}/merge` — `ticket0/merge`
   */
  merge(input: { conversationId: string; intoConversationId: string }): Promise<Conversation>;

  /**
   * Your own conversations
   *
   * `GET /me/conversations` — `ticket0/my-conversations`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  myConversations(): Promise<Paged<Conversation>>;

  /**
   * The public messages on one of your conversations
   *
   * `GET /me/conversations/{conversationId}/messages` — `ticket0/my-messages`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  myMessages(input: { conversationId: string }): Promise<Paged<({ id: string; conversation_id: string; author_kind: "contact" | "agent" | "assistant" | "system"; visibility: "public" | "internal"; body_text: string; body_html: string | null; email_message_id: string | null; email_in_reply_to: string | null; delivered_at: string | null; cited_article_ids: string | null; created_at: string; citations: { id: string; title: string; url: string; headingPath: string }[] })>>;

  /**
   * What you have not read yet
   *
   * `GET /me/notifications` — `ticket0/my-notifications`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  myNotifications(): Promise<Paged<Notification>>;

  /**
   * Leave an internal note colleagues can see and the customer cannot
   *
   * `POST /conversations/{conversationId}/notes` — `ticket0/post-note`
   */
  postNote(input: { conversationId: string; body: string }): Promise<Message>;

  /**
   * Reply to the customer
   *
   * `POST /conversations/{conversationId}/replies` — `ticket0/post-public-reply`
   */
  postPublicReply(input: { conversationId: string; body: string; bodyHtml?: string | null; citedArticleIds?: string[] }): Promise<Message>;

  /**
   * Read a message the relay is about to send
   *
   * `GET /relay/outbound/{messageId}` — `ticket0/read-outbound`
   */
  readOutbound(input: { messageId: string }): Promise<{ messageId: string; conversationId: string; subject: string; toEmail: string | null; fromAddress: string; agentName: string | null; bodyText: string | null; bodyHtml: string | null; emailInReplyTo: string | null }>;

  /**
   * Record an assistant answer and its token usage
   *
   * `POST /conversations/{conversationId}/answers` — `ticket0/record-answer`
   */
  recordAnswer(input: { conversationId: string; turnId: string; model: string; body: string; inputTokens: number; outputTokens: number; citedArticleIds: string[]; confidence?: number | null; outcome: "drafted" | "answered" | "escalated" | "failed"; error?: string; usage?: { attribution: { tenant: string; scope: string; vertical: string; version: string; operation: string }; model: string; provider: string; modelId: string; reported: boolean; inputTokens: number; outputTokens: number; cachedInputTokens: number; cacheWriteTokens: number; listUsd: string | null; at: string; elapsedMs: number } }): Promise<AiTurn>;

  /**
   * Record that the assistant could not act on a message
   *
   * `POST /conversations/{conversationId}/assistant-failures` — `ticket0/record-assistant-failure`
   */
  recordAssistantFailure(input: { conversationId: string; turnId: string; model: string; error: string }): Promise<AiTurn>;

  /**
   * Record that the relay delivered a message
   *
   * `POST /relay/outbound/{messageId}/delivered` — `ticket0/record-delivery`
   */
  recordDelivery(input: { messageId: string; emailMessageId: string }): Promise<Message>;

  /**
   * Record the articles an ingest produced
   *
   * `POST /kb/sources/{sourceId}/articles` — `ticket0/record-kb-articles`
   */
  recordKbArticles(input: { sourceId: string; articles: { url: string; title: string; headingPath: string; body: string }[] }): Promise<{ sourceId: string; added: number; updated: number; unchanged: number }>;

  /**
   * Record that a documentation source could not be read
   *
   * `POST /kb/sources/{sourceId}/failure` — `ticket0/record-kb-ingest-failure`
   */
  recordKbIngestFailure(input: { sourceId: string; error: string }): Promise<KbSource>;

  /**
   * A canned answer with this conversation’s facts filled in
   *
   * `GET /conversations/{conversationId}/saved-replies/{savedReplyId}/render` — `ticket0/render-saved-reply`
   */
  renderSavedReply(input: { conversationId: string; savedReplyId: string }): Promise<{ id: string; title: string; body: string; blank: string[]; unresolved: string[] }>;

  /**
   * Mark a conversation resolved
   *
   * `POST /conversations/{conversationId}/resolve` — `ticket0/resolve`
   */
  resolve(input: { conversationId: string }): Promise<Conversation>;

  /**
   * Issue a new identity-verification secret (shown once)
   *
   * `POST /desk/verification-secret` — `ticket0/rotate-verification-secret`
   */
  rotateVerificationSecret(): Promise<{ id: string; secret: string; rotatedAt: string }>;

  /**
   * Find a person by email or name
   *
   * `GET /contacts/search` — `ticket0/search-contacts`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  searchContacts(input: { q: string }): Promise<Paged<Contact>>;

  /**
   * Find a conversation by subject or by what was said in it
   *
   * `GET /conversations/search` — `ticket0/search-conversations`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  searchConversations(input: { q: string; state?: "new" | "open" | "snoozed" | "resolved" | "closed"; assignee?: string; channel?: "widget" | "email"; priority?: "low" | "normal" | "urgent" }): Promise<Paged<Conversation>>;

  /**
   * Search the knowledge base
   *
   * `GET /kb/search` — `ticket0/search-kb`
   */
  searchKb(input: { q: string; sourceId?: string; limit?: number }): Promise<{ results: { id: string; source_id: string; url: string; title: string; heading_path: string; body: string; content_hash: string; ingested_at: string; snippet: string; rank: number }[]; limit: number; capped: boolean }>;

  /**
   * Set your own display name and signature
   *
   * `PUT /agents/me` — `ticket0/set-agent-profile`
   */
  setAgentProfile(input: { displayName: string; avatarUrl: string | null; signature: string | null }): Promise<AgentProfile>;

  /**
   * Set a conversation's priority
   *
   * `POST /conversations/{conversationId}/priority` — `ticket0/set-priority`
   */
  setPriority(input: { conversationId: string; priority: "low" | "normal" | "urgent" }): Promise<Conversation>;

  /**
   * Set the price of a meter from a date
   *
   * `POST /usage/rates` — `ticket0/set-usage-rate`
   */
  setUsageRate(input: { meterKey: string; unitPrice: string; currency: string; effectiveFrom: string }): Promise<UsageRate>;

  /**
   * Park a conversation until a time
   *
   * `POST /conversations/{conversationId}/snooze` — `ticket0/snooze`
   */
  snooze(input: { conversationId: string; until: string }): Promise<Conversation>;

  /**
   * Rate how the conversation went
   *
   * `POST /me/conversations/{conversationId}/csat` — `ticket0/submit-csat`
   */
  submitCsat(input: { conversationId: string; score: number; comment?: string | null }): Promise<Csat>;

  /**
   * Tag a conversation
   *
   * `POST /conversations/{conversationId}/tags` — `ticket0/tag-conversation`
   */
  tagConversation(input: { conversationId: string; tag: string }): Promise<ConversationTag>;

  /**
   * Take a tag off a conversation
   *
   * `DELETE /conversations/{conversationId}/tags/{tag}` — `ticket0/untag-conversation`
   */
  untagConversation(input: { conversationId: string; tag: string }): Promise<{ conversation_id: string; tag: string; removed: boolean }>;

  /**
   * Change a canned answer
   *
   * `PATCH /saved-replies/{savedReplyId}` — `ticket0/update-saved-reply`
   *
   * Concurrency-checked over `savedReply`. The tag this answers with is
   * remembered and sent as `If-Match` on the next write to the same entity, so a
   * write that would overwrite someone else's change fails with 412 instead.
   */
  updateSavedReply(input: { savedReplyId: string; title?: string; body?: string }): Promise<SavedReply>;

  /**
   * Token usage and what it cost
   *
   * `GET /usage` — `ticket0/usage-summary`
   */
  usageSummary(input: { from?: string; to?: string; conversationId?: string }): Promise<{ from: string; to: string; currency: string; total: string; lines: { meterKey: string; unit: string; qty: string; unitPrice: string; amount: string; entryCount: number }[] }>;

  /**
   * Un-snooze a conversation
   *
   * `POST /conversations/{conversationId}/wake` — `ticket0/wake`
   */
  wake(input: { conversationId: string }): Promise<Conversation>;

  /**
   * The origins this desk may be embedded on
   *
   * `GET /widget/origins` — `ticket0/widget-origins`
   */
  widgetOrigins(): Promise<{ origins: string[] }>;

  /**
   * Say something in the widget
   *
   * `POST /widget/sessions/{sessionId}/messages` — `ticket0/widget-post`
   */
  widgetPost(input: { sessionId: string; token: string; body: string }): Promise<Message>;

  /**
   * The browser session behind a widget conversation
   *
   * `GET /conversations/{conversationId}/widget-session` — `ticket0/widget-session`
   */
  widgetSession(input: { conversationId: string }): Promise<{ session: { id: string; conversation_id: string; contact_id: string; origin: string; started_at: string; last_seen_at: string; user_agent: string | null; language: string | null; browser: string | null; browser_version: string | null; os: string | null; os_version: string | null; device: "desktop" | "mobile" | "tablet" | "bot" | "unknown" | null; country: string | null; region: string | null; city: string | null; timezone: string | null } | null }>;

  /**
   * Open a chat session from an embedded widget
   *
   * `POST /widget/sessions` — `ticket0/widget-start`
   */
  widgetStart(input: { origin: string; client?: { userAgent: string | null; language: string | null; device: { browser: string | null; browserVersion: string | null; os: string | null; osVersion: string | null; kind: "desktop" | "mobile" | "tablet" | "bot" | "unknown" }; geo: { country: string | null; region: string | null; city: string | null; timezone: string | null; continent: string | null } }; identity?: { externalId: string; email?: string | null; displayName?: string | null; signature: string } | null }): Promise<{ sessionId: string; token: string; greeting: string; verified: boolean; origin: string; startedAt: string }>;

  /**
   * The public messages in this session’s conversation
   *
   * `GET /widget/sessions/{sessionId}/messages` — `ticket0/widget-thread`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  widgetThread(input: { sessionId: string; token: string }): Promise<Paged<({ id: string; conversation_id: string; author_kind: "contact" | "agent" | "assistant" | "system"; visibility: "public" | "internal"; body_text: string; body_html: string | null; email_message_id: string | null; email_in_reply_to: string | null; delivered_at: string | null; cited_article_ids: string | null; created_at: string; citations: { id: string; title: string; url: string; headingPath: string }[] })>>;

  /**
   * The entity tags this client is holding, keyed `entityType:id` (#129).
   *
   * Populated from every concurrency-checked response and sent back as
   * `If-Match` on the next write to that entity — an app writes no header code.
   * Exposed rather than hidden so it can be inspected in a devtools session and
   * cleared when a screen is abandoned; a stale tag causes a 412, never a silent
   * overwrite, so clearing it is safe and keeping it is safe.
   */
  readonly versions: Map<string, string>;

  /**
   * Fetch the next page of any paged read, given a previous page's `next`.
   *
   * One method for every paged read rather than one per read: `next` is a URL that
   * already carries the filters, so there is nothing left for a caller to restate.
   */
  follow<T>(next: string): Promise<Paged<T>>;
}

/**
 * The plumbing below is deliberately untyped against the interface above, and cast
 * once at the end.
 *
 * `send` cannot know an operation's return type — it has a `Response`, not a schema
 * — so every method would otherwise need its own `as` and the file would carry
 * fourteen casts instead of one. The interface is what a caller sees, and it IS
 * derived from the model; this is the seam where a runtime that speaks `unknown`
 * meets it.
 */
type Args = Record<string, unknown>;

const omit = (input: Record<string, unknown>, keys: string[]): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(input ?? {})) if (!keys.includes(k)) out[k] = v;
  return out;
};

/** Declared fields become a query string; `undefined` is absent rather than the string "undefined". */
const query = (values: Record<string, unknown> | undefined): string => {
  if (!values) return '';
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(values)) {
    if (v === undefined || v === null) continue;
    params.set(k, String(v));
  }
  const s = params.toString();
  return s ? `?${s}` : '';
};

/**
 * The `rel="next"` URL out of an RFC 8288 `Link` header, or null.
 *
 * Only `next` is looked for because only `next` is sent: keyset paging walks one
 * way and does not know its own offset, so there is no `prev`, `first` or `last`
 * to honour. A header naming some other relation is not this walk's.
 */
const nextFrom = (header: string | null): string | null => {
  if (!header) return null;
  for (const part of header.split(',')) {
    const match = /^\s*<([^>]+)>\s*;\s*(.+)$/.exec(part);
    if (match && /rel\s*=\s*"?next"?/.test(match[2] as string)) return match[1] as string;
  }
  return null;
};

export function createClient(options: ClientOptions = {}): Ticket0Client {
  const baseUrl = options.baseUrl ?? '/api';
  const doFetch = options.fetch ?? globalThis.fetch.bind(globalThis);
  const readMessage = options.errorMessage ?? defaultErrorMessage;
  /** #129: entity tags seen on this client, keyed `entityType:id`. */
  const versions = new Map<string, string>();

  /** One request, against a path that is ALREADY prefixed and query-stringed. */
  const raw = async (fullPath: string, method: string, body: unknown, extra?: Record<string, string>): Promise<Response> => {
    const hasBody = body !== undefined && method !== 'GET' && method !== 'DELETE';
    return await doFetch(fullPath, {
      method,
      headers: {
        ...(hasBody ? { 'content-type': 'application/json' } : {}),
        ...(options.headers?.() ?? {}),
        ...(extra ?? {}),
      },
      ...(hasBody ? { body: JSON.stringify(body) } : {}),
    });
  };

  const parse = async (res: Response): Promise<unknown> => {
    const text = await res.text();
    const body: unknown = text ? JSON.parse(text) : null;
    if (!res.ok) throw new ApiError(res.status, readMessage(body, res) ?? res.statusText, body);
    return body;
  };

  const send = async (path: string, method: string, body: unknown, params: unknown): Promise<unknown> =>
    await parse(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  /**
   * A concurrency-checked call (#129): remember the tag a read hands back, send it
   * as `If-Match` on the next write to that same entity.
   *
   * This is what makes the guarantee reachable without the app writing header code.
   * The tag is per (entity type, id) rather than global — two facilities being
   * edited in two tabs do not share one — and it lives on the CLIENT INSTANCE, so a
   * page reload starts empty and the first write after it simply goes unconditional
   * until something has been read.
   *
   * **A 412 evicts the tag rather than replacing it with the current one.** The
   * tempting behaviour is to re-read and retry automatically; that would overwrite
   * whatever change caused the refusal, which is the lost update this exists to
   * prevent. Evicting means the app's own re-read is what re-arms the guard, and
   * until it happens the next write is unconditional — visibly wrong rather than
   * quietly wrong.
   *
   * `versions` is exposed on the client so an app can inspect or clear it. Nothing
   * here is hidden state a caller cannot reach.
   */
  const guarded = async (
    entityType: string,
    entityId: unknown,
    path: string,
    method: string,
    body: unknown,
    params: unknown,
  ): Promise<unknown> => {
    const key = `${entityType}:${String(entityId)}`;
    const held = versions.get(key);
    const res = await raw(
      `${baseUrl}${path}${query(params as Record<string, unknown>)}`,
      method,
      body,
      held !== undefined && method !== 'GET' ? { 'If-Match': held } : undefined,
    );
    if (res.status === 412) versions.delete(key);
    const parsed = await parse(res);
    // Read AFTER `parse`, which throws on a failure — a tag from an error response
    // describes nothing the caller now holds.
    const tag = res.headers.get('ETag');
    if (tag) versions.set(key, tag);
    return parsed;
  };

  /**
   * A paged read: the entries come from the body, the walk from the headers.
   *
   * A cross-origin caller reads neither header without `Access-Control-Expose-Headers`,
   * and the symptom is not an error — it is a list that looks like it has one page. Under
   * a same-origin dev proxy (this demo) or a same-origin deployment, both are readable.
   */
  const readPage = async (res: Response): Promise<Paged<unknown>> => {
    const entries = (await parse(res)) as unknown[];
    const total = res.headers.get('X-Total-Count');
    return { entries, next: nextFrom(res.headers.get('Link')), total: total === null ? null : Number(total) };
  };

  const page = async (path: string, method: string, body: unknown, params: unknown): Promise<Paged<unknown>> =>
    await readPage(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  return {
    addKbSource: (input: Args) =>
      send("/kb/sources", "POST", input, undefined),
    assign: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/assignee`, "POST", omit(input, ["conversationId"]), undefined),
    assistantHealth: () =>
      send("/assistant/health", "GET", undefined, undefined),
    close: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/close`, "POST", omit(input, ["conversationId"]), undefined),
    closeUsagePeriod: (input: Args) =>
      send("/usage/periods", "POST", input, undefined),
    configureDesk: (input: Args) =>
      send("/desk", "PATCH", input, undefined),
    createSavedReply: (input: Args) =>
      send("/saved-replies", "POST", input, undefined),
    deleteSavedReply: (input: Args) =>
      guarded("savedReply", input.savedReplyId, `/saved-replies/${encodeURIComponent(String(input.savedReplyId))}`, "DELETE", undefined, omit(input, ["savedReplyId"])),
    deskMetrics: (input: Args) =>
      send("/desk-metrics", "GET", undefined, input),
    getConversation: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}`, "GET", undefined, omit(input, ["conversationId"])),
    getCsat: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/csat`, "GET", undefined, omit(input, ["conversationId"])),
    getDesk: () =>
      send("/desk", "GET", undefined, undefined),
    getSavedReply: (input: Args) =>
      guarded("savedReply", input.savedReplyId, `/saved-replies/${encodeURIComponent(String(input.savedReplyId))}`, "GET", undefined, omit(input, ["savedReplyId"])),
    ingestKbSource: (input: Args) =>
      send(`/kb/sources/${encodeURIComponent(String(input.sourceId))}/ingest`, "POST", omit(input, ["sourceId"]), undefined),
    ingestMessage: (input: Args) =>
      send("/relay/inbound", "POST", input, undefined),
    listAgents: () =>
      page("/agents", "GET", undefined, undefined),
    listContacts: () =>
      page("/contacts", "GET", undefined, undefined),
    listConversationTags: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/tags`, "GET", undefined, omit(input, ["conversationId"])),
    listConversations: (input: Args) =>
      page("/conversations", "GET", undefined, input),
    listKbSources: () =>
      page("/kb/sources", "GET", undefined, undefined),
    listMessages: (input: Args) =>
      page(`/conversations/${encodeURIComponent(String(input.conversationId))}/messages`, "GET", undefined, omit(input, ["conversationId"])),
    listSavedReplies: () =>
      page("/saved-replies", "GET", undefined, undefined),
    listTags: () =>
      send("/tags", "GET", undefined, undefined),
    listTurns: (input: Args) =>
      page(`/conversations/${encodeURIComponent(String(input.conversationId))}/turns`, "GET", undefined, omit(input, ["conversationId"])),
    markNotificationRead: (input: Args) =>
      send(`/me/notifications/${encodeURIComponent(String(input.notificationId))}/read`, "POST", omit(input, ["notificationId"]), undefined),
    merge: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/merge`, "POST", omit(input, ["conversationId"]), undefined),
    myConversations: () =>
      page("/me/conversations", "GET", undefined, undefined),
    myMessages: (input: Args) =>
      page(`/me/conversations/${encodeURIComponent(String(input.conversationId))}/messages`, "GET", undefined, omit(input, ["conversationId"])),
    myNotifications: () =>
      page("/me/notifications", "GET", undefined, undefined),
    postNote: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/notes`, "POST", omit(input, ["conversationId"]), undefined),
    postPublicReply: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/replies`, "POST", omit(input, ["conversationId"]), undefined),
    readOutbound: (input: Args) =>
      send(`/relay/outbound/${encodeURIComponent(String(input.messageId))}`, "GET", undefined, omit(input, ["messageId"])),
    recordAnswer: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/answers`, "POST", omit(input, ["conversationId"]), undefined),
    recordAssistantFailure: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/assistant-failures`, "POST", omit(input, ["conversationId"]), undefined),
    recordDelivery: (input: Args) =>
      send(`/relay/outbound/${encodeURIComponent(String(input.messageId))}/delivered`, "POST", omit(input, ["messageId"]), undefined),
    recordKbArticles: (input: Args) =>
      send(`/kb/sources/${encodeURIComponent(String(input.sourceId))}/articles`, "POST", omit(input, ["sourceId"]), undefined),
    recordKbIngestFailure: (input: Args) =>
      send(`/kb/sources/${encodeURIComponent(String(input.sourceId))}/failure`, "POST", omit(input, ["sourceId"]), undefined),
    renderSavedReply: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/saved-replies/${encodeURIComponent(String(input.savedReplyId))}/render`, "GET", undefined, omit(input, ["conversationId","savedReplyId"])),
    resolve: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/resolve`, "POST", omit(input, ["conversationId"]), undefined),
    rotateVerificationSecret: () =>
      send("/desk/verification-secret", "POST", undefined, undefined),
    searchContacts: (input: Args) =>
      page("/contacts/search", "GET", undefined, input),
    searchConversations: (input: Args) =>
      page("/conversations/search", "GET", undefined, input),
    searchKb: (input: Args) =>
      send("/kb/search", "GET", undefined, input),
    setAgentProfile: (input: Args) =>
      send("/agents/me", "PUT", input, undefined),
    setPriority: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/priority`, "POST", omit(input, ["conversationId"]), undefined),
    setUsageRate: (input: Args) =>
      send("/usage/rates", "POST", input, undefined),
    snooze: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/snooze`, "POST", omit(input, ["conversationId"]), undefined),
    submitCsat: (input: Args) =>
      send(`/me/conversations/${encodeURIComponent(String(input.conversationId))}/csat`, "POST", omit(input, ["conversationId"]), undefined),
    tagConversation: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/tags`, "POST", omit(input, ["conversationId"]), undefined),
    untagConversation: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/tags/${encodeURIComponent(String(input.tag))}`, "DELETE", undefined, omit(input, ["conversationId","tag"])),
    updateSavedReply: (input: Args) =>
      guarded("savedReply", input.savedReplyId, `/saved-replies/${encodeURIComponent(String(input.savedReplyId))}`, "PATCH", omit(input, ["savedReplyId"]), undefined),
    usageSummary: (input: Args) =>
      send("/usage", "GET", undefined, input),
    wake: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/wake`, "POST", omit(input, ["conversationId"]), undefined),
    widgetOrigins: () =>
      send("/widget/origins", "GET", undefined, undefined),
    widgetPost: (input: Args) =>
      send(`/widget/sessions/${encodeURIComponent(String(input.sessionId))}/messages`, "POST", omit(input, ["sessionId"]), undefined),
    widgetSession: (input: Args) =>
      send(`/conversations/${encodeURIComponent(String(input.conversationId))}/widget-session`, "GET", undefined, omit(input, ["conversationId"])),
    widgetStart: (input: Args) =>
      send("/widget/sessions", "POST", input, undefined),
    widgetThread: (input: Args) =>
      page(`/widget/sessions/${encodeURIComponent(String(input.sessionId))}/messages`, "GET", undefined, omit(input, ["sessionId"])),
    versions,
    follow: async (next: string) => {
      // The link names the API's OWN origin, which under a dev proxy is not the origin
      // this page was served from. So the path is kept and the origin is taken from
      // whatever this client was configured to talk to: relative for a browser, which
      // keeps the request same-origin, absolute for a harness that has no page.
      const link = new URL(next, 'http://substrat.invalid');
      const target = /^https?:\/\//.test(baseUrl)
        ? new URL(link.pathname + link.search, baseUrl).href
        : link.pathname + link.search;
      return await readPage(await raw(target, 'GET', undefined));
    },
  } as unknown as Ticket0Client;
}
