/**
 * Every string GuardPath renders, and the markdown twin of the same facts.
 *
 * As with its siblings: a fact typed into the template renders on the page and
 * vanishes from llms.txt. Put it here. See ./LayerStack.content.mts.
 *
 * The ordering is load-bearing and is not decoration. These are not layers of a
 * picture — they are stages a commit passes through in time, each able to stop
 * it, and the claim the page makes is that a mistake surviving one meets the
 * next. Reordering them makes the page say something false.
 */

/** One stage on the path a change takes. `body` carries inline `<code>`/`<em>`. */
export interface Guard {
  /** When it fires — the stage name, not a category. */
  readonly when: string;
  readonly title: string;
  readonly body: string;
  /** What a reader loses if this stage is missing. */
  readonly stops: string;
}

export const guards: readonly Guard[] = [
  {
    when: 'Compile',
    title: "Invalid states don't typecheck",
    body:
      'A narrow, aggressively typed SDK means a small hallucination surface. A ' +
      '<code>ScopeId</code> will not typecheck where a <code>TenantId</code> is expected, so an ' +
      'agent cannot swap them silently. A permission <code>Decision</code> is either ' +
      '<code>{ allowed: true, proof }</code> or <code>{ allowed: false, checked, node }</code> — an ' +
      'unexplained allow is unrepresentable. An event without a <code>piiClass</code> ' +
      "doesn't parse, and a PII-classed event without a <code>subjectId</code> doesn't either.",
    stops: 'ID confusion, silent allows, unclassified personal data.',
  },
  {
    when: 'Bound',
    title: 'The shortcut is told apart from the sanctioned path',
    body:
      'Most guardrails fail loud. The layer rules are the ones that fail <em>silently</em> — a ' +
      "raw <code>SELECT</code> against an engine's private table returns the right rows, the test " +
      'passes, and nothing tells you that engine can now never ship a migration. ' +
      '<code>boundary-lint</code> is the only thing that can see it.',
    stops: 'Raw DB access, cross-module reads, forged audit rows, ambient secrets.',
  },
  {
    when: 'Derive',
    title: 'What can be derived is never generated',
    body:
      'Wherever an artifact can be <em>derived</em>, it is derived by code, not by a model. ' +
      'Entities are declared once; the DDL, the API surface, the browser client and the ' +
      'permission table are emitted from that declaration, and CI re-emits each and fails ' +
      'on drift. Code generated by code beats code generated by a model on tokens, latency ' +
      'and exactness at once.',
    stops: 'Hand-edits to shipped SQL, drifted clients, a widened role merging unseen.',
  },
  {
    when: 'Judge',
    title: 'The build may not edit its own oracle',
    body:
      'Models fail quietly and inconsistently rather than loudly, and you cannot prompt that ' +
      'away — so the architecture has to catch it. Every defect worth catching is two ' +
      'descriptions disagreeing. Once the code is derived from the model it can no longer ' +
      'contradict it, so the second description has to come from somewhere else entirely.',
    stops: 'A suite that ratifies a wrong model perfectly and forever.',
  },
  {
    when: 'Review',
    title: 'Two things an agent never self-approves',
    body:
      'Schema migrations and permission definitions stay under human review even in a fully ' +
      'agent-driven shop. Both are read as a diff, and CI re-emits the artifact and fails on ' +
      'drift — which is what makes the reading unskippable. The red build is not the ' +
      'approval; it is what stops the approval being skipped.',
    stops: 'A destructive migration or a quietly widened role reaching main.',
  },
  {
    when: 'Rehearse',
    title: 'A running copy of production to be wrong in',
    body:
      'Reviewing a migration diff is a checkpoint. Watching that migration run against a copy ' +
      'of the real data is what makes the checkpoint honest. Crossing a migration-digest ' +
      'boundary snapshots the prior state first — the digest comparison is the gate, not a ' +
      'flag someone remembers to pass.',
    stops: "Version 2 landing on version 1's live data.",
  },
];

/** The heading the figure carries, kept beside the data it describes. */
export const head = {
  label: 'the path',
  lede: 'Six guards, in the order they fire.',
};

/**
 * Markup the figure wants, rendered as the markdown the twin wants.
 *
 * Mapped rather than stripped (the sibling LayerStack strips, which is fine for
 * prose that carries no code): `ScopeId` and `ctx.sql` are the substance of these
 * sentences, and a twin that flattens them to bare words reads as if the rule were
 * about the English word rather than the symbol.
 */
const plain = (html: string) =>
  html
    .replace(/<code>([^<]*)<\/code>/g, '`$1`')
    .replace(/<em>([^<]*)<\/em>/g, '*$1*')
    .replace(/<(?:b|strong)>([^<]*)<\/(?:b|strong)>/g, '**$1**')
    .replace(/\s+/g, ' ')
    .trim();

export function alt(): string {
  return [
    `**Diagram — ${head.label}.** ${head.lede} Each stage can stop a change, and the ` +
      'claim is that a mistake surviving one meets the next.',
    '',
    ...guards.map(
      (g, i) =>
        `${i + 1}. **${g.when} — ${g.title}.** ${plain(g.body)}\n` +
        `   - *Stops:* ${g.stops}`,
    ),
  ].join('\n');
}
