// GENERATED by tools/client-emit.mts from src/entities.ts + src/operations.ts + @substrat-run/engine-workorder + @substrat-run/engine-protocol + @substrat-run/engine-invoicing + @substrat-run/contracts — do not edit by hand.
//
// HAND-STATED TYPES (substrat.client.types). These schemas have no inferable input
// type — a `z.preprocess` infers `unknown` by construction — so the type below was
// decided by a person, not derived, and is not checked against the schema:
//   protocol/define-template.input.content → unknown
//
// Re-emit with `pnpm lint:client`; CI runs `pnpm lint:client --check` and fails on
// drift, so the client cannot fall behind the model the way a hand-written one did.
//
// Standalone on purpose: no imports, so the browser bundle carries no schema library
// and `tools/declared-deps.mjs` has nothing to object to.

/** A failed request. `status` is the interesting field — 403 is the permission model answering. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
    readonly body: unknown,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

export interface ClientOptions {
  /** Prefixed to every declared path. Matches `mountOperations`' own default. */
  baseUrl?: string;
  /** Per-request headers — an auth token, or this demo's `x-principal` persona seam. */
  headers?: () => Record<string, string>;
  /** Injectable so the client works under a test harness, not only in a browser. */
  fetch?: typeof globalThis.fetch;
  /**
   * Pull a message out of an error body.
   *
   * The one thing here the model does NOT declare: a vertical picks its error
   * envelope in its own `app.onError`, so this is a best effort over the shapes in
   * use — `{ error }`, and problem+json's `detail`/`title` — and an app that
   * answers something else says so here rather than being guessed at.
   */
  errorMessage?: (body: unknown, response: Response) => string | undefined;
}

function defaultErrorMessage(body: unknown): string | undefined {
  if (typeof body !== 'object' || body === null) return undefined;
  const b = body as Record<string, unknown>;
  for (const key of ['error', 'detail', 'title', 'message']) {
    if (typeof b[key] === 'string') return b[key] as string;
  }
  return undefined;
}


/** `callout_customers` — declared in src/entities.ts + src/operations.ts + @substrat-run/engine-workorder + @substrat-run/engine-protocol + @substrat-run/engine-invoicing + @substrat-run/contracts. */
export interface Customer {
  id: string;
  number: string;
  name: string;
  org_ref: string | null;
  created_at: string;
}

/** `callout_facilities` — declared in src/entities.ts + src/operations.ts + @substrat-run/engine-workorder + @substrat-run/engine-protocol + @substrat-run/engine-invoicing + @substrat-run/contracts. */
export interface Facility {
  id: string;
  customer_id: string;
  name: string;
  address: string | null;
  access_note: string | null;
  created_at: string;
}

/** `workorder_orders` — declared in src/entities.ts + src/operations.ts + @substrat-run/engine-workorder + @substrat-run/engine-protocol + @substrat-run/engine-invoicing + @substrat-run/contracts. */
export interface Workorder {
  id: string;
  number: number;
  facility_type: string;
  facility_id: string;
  customer_type: string;
  customer_id: string;
  kind: string;
  title: string;
  description: string | null;
  status: "planned" | "in_progress" | "completed" | "closed";
  assigned_to: string | null;
  created_by: string;
  created_at: string;
  completed_at: string | null;
}

/** `protocol_instances` — declared in src/entities.ts + src/operations.ts + @substrat-run/engine-workorder + @substrat-run/engine-protocol + @substrat-run/engine-invoicing + @substrat-run/contracts. */
export interface Protocol {
  id: string;
  template_key: string;
  template_version: number;
  entity_type: string;
  entity_id: string;
  status: "open" | "pending_signature" | "signed" | "voided";
  created_by: string;
  created_at: string;
  voided_by: string | null;
  voided_reason: string | null;
  voided_at: string | null;
  content_ref_type: string | null;
  content_ref_id: string | null;
  bound_hash: string | null;
  document_attachment_id: string | null;
  frozen_hash: string | null;
  frozen_at: string | null;
}

/** `invoicing_underlag` — declared in src/entities.ts + src/operations.ts + @substrat-run/engine-workorder + @substrat-run/engine-protocol + @substrat-run/engine-invoicing + @substrat-run/contracts. */
export interface Underlag {
  id: string;
  number: number;
  customer_type: string;
  customer_id: string;
  status: "open" | "exported";
  created_at: string;
  exported_at: string | null;
}

/** `priceRow` — a published schema, not a stored row. */
export interface Price {
  article: string;
  description: string;
  unit: string;
  price_amount: string;
  currency: string;
  min_qty: string | null;
  internal: number;
}

/** `money` — a published schema, not a stored row. */
export interface Money {
  amount: string;
  currency: string;
}

/** `workOrder` — a published schema, not a stored row. */
export interface WorkOrder {
  id: string;
  number: number;
  facility: { entityType: string; entityId: string };
  customer: { entityType: string; entityId: string };
  kind: string;
  title: string;
  description: string | null;
  status: "planned" | "in_progress" | "completed" | "closed";
  assignedTo: string | null;
  createdBy: string;
  createdAt: string;
  completedAt: string | null;
}

/** `billableLine` — a published schema, not a stored row. */
export interface BillableLine {
  article: string;
  description: string;
  qty: string;
  unit: string;
  unitPrice: Money;
  lineTotal: Money;
  sourceType: "time" | "material";
  sourceId: string;
}

/** `materialLine` — a published schema, not a stored row. */
export interface MaterialLine {
  id: string;
  order_id: string;
  article: string;
  qty: string;
  note: string | null;
  reported_by: string;
  reported_at: string;
}

/** `protocolInstanceRow` — a published schema, not a stored row. */
export interface ProtocolInstance {
  id: string;
  template_key: string;
  template_version: number;
  entity_type: string;
  entity_id: string;
  status: "open" | "pending_signature" | "signed" | "voided";
  created_by: string;
  created_at: string;
  voided_by: string | null;
  voided_reason: string | null;
  voided_at: string | null;
  content_ref_type: string | null;
  content_ref_id: string | null;
  bound_hash: string | null;
  document_attachment_id: string | null;
  frozen_hash: string | null;
  frozen_at: string | null;
}

/** `protocolTemplateRow` — a published schema, not a stored row. */
export interface ProtocolTemplateRow {
  id: string;
  key: string;
  version: number;
  title: string;
  content_json: string;
  created_at: string;
}

/** `protocolResponseRow` — a published schema, not a stored row. */
export interface ProtocolResponse {
  id: string;
  instance_id: string;
  item_key: string;
  value_json: string;
  note: string | null;
  responded_by: string;
  responded_at: string;
}

/** `protocolSignatureRow` — a published schema, not a stored row. */
export interface ProtocolSignature {
  id: string;
  instance_id: string;
  signed_by: string;
  kind: "primary" | "counter";
  method: string;
  content_hash: string;
  evidence_ref: string | null;
  signed_at: string;
  request_id: string | null;
  signatory_kind: "principal" | "external";
  signatory_label: string | null;
}

/** `protocolSignatureRequestRow` — a published schema, not a stored row. */
export interface ProtocolSignatureRequest {
  id: string;
  instance_id: string;
  party_label: string;
  party_kind: "principal" | "external";
  party_ref: string | null;
  signature_kind: "primary" | "counter";
  method: string;
  auth_level: "basic" | "strong" | null;
  contact_key_id: string | null;
  contact_ciphertext: string | null;
  status: "pending" | "signed" | "declined" | "expired" | "cancelled";
  content_hash: string;
  external_ref: string | null;
  resolved_note: string | null;
  requested_by: string;
  requested_at: string;
  resolved_at: string | null;
}

/** `underlagLine` — a published schema, not a stored row. */
export interface UnderlagLine {
  id: string;
  underlag_id: string;
  document_type: string;
  document_id: string;
  source_type: string | null;
  source_id: string | null;
  article: string;
  description: string;
  qty: string;
  unit: string;
  unit_price_amount: string;
  currency: string;
  line_total_amount: string;
  created_at: string;
}

/** `underlagListRow` — a published schema, not a stored row. */
export interface UnderlagListRow {
  id: string;
  number: number;
  customer_type: string;
  customer_id: string;
  status: "open" | "exported";
  created_at: string;
  exported_at: string | null;
  total: string;
}

/** Every operation this vertical binds to HTTP, one method each. */
export interface CalloutClient {
  /**
   * Complete a work order and price its billable lines
   *
   * `POST /workorders/{orderId}/complete` — `callout/complete-workorder`
   */
  completeWorkorder(input: { orderId: string }): Promise<{ order: WorkOrder; billable: BillableLine[]; total: Money }>;

  /**
   * Register a customer
   *
   * `POST /customers` — `callout/create-customer`
   */
  createCustomer(input: { number: string; name: string; orgRef?: string }): Promise<Customer>;

  /**
   * Register a facility for a customer
   *
   * `POST /customers/{customerId}/facilities` — `callout/create-facility`
   */
  createFacility(input: { customerId: string; name: string; address?: string; accessNote?: string }): Promise<Facility>;

  /**
   * Open a work order against a facility
   *
   * `POST /workorders` — `callout/create-workorder`
   */
  createWorkorder(input: { facilityId: string; kind: string; title: string; description?: string }): Promise<WorkOrder>;

  /**
   * Instantiate a protocol against an entity
   *
   * `POST /workorders/{entityId}/protocols` — `callout/instantiate-protocol`
   */
  instantiateProtocol(input: { templateKey: string; entityType: "workorder"; entityId: string }): Promise<ProtocolInstance>;

  /**
   * List customers with their facilities
   *
   * `GET /customers` — `callout/list-customers`
   */
  listCustomers(): Promise<({ id: string; number: string; name: string; org_ref: string | null; created_at: string; facilities: Facility[] })[]>;

  /**
   * The work orders visible to the caller's portal
   *
   * `GET /portal/orders` — `callout/portal-orders`
   */
  portalOrders(): Promise<WorkOrder[]>;

  /**
   * The current price list
   *
   * `GET /prices` — `callout/price-list`
   */
  priceList(): Promise<Price[]>;

  /**
   * Find customers by name or number
   *
   * `GET /customers/search` — `callout/search-customers`
   */
  searchCustomers(input: { q: string; limit?: number }): Promise<{ results: Customer[]; limit: number; capped: boolean }>;

  /**
   * Create or update a price-list article
   *
   * `POST /prices` — `callout/upsert-price`
   */
  upsertPrice(input: { article: string; description: string; unit: string; priceAmount: string; currency?: string; minQty?: string; internal?: boolean }): Promise<Price>;

  /**
   * Export an invoice basis — makes it immutable
   *
   * `POST /invoicing/{underlagId}/export` — `invoicing/export`
   */
  invoicingExport(input: { underlagId: string }): Promise<Underlag>;

  /**
   * One invoice basis with its lines and total
   *
   * `GET /invoicing/{underlagId}` — `invoicing/get`
   */
  invoicingGet(input: { underlagId: string }): Promise<{ underlag: Underlag; lines: UnderlagLine[]; total: string }>;

  /**
   * Invoice bases, newest first, optionally filtered by status
   *
   * `GET /invoicing` — `invoicing/list`
   */
  invoicingList(input: { status?: string }): Promise<UnderlagListRow[]>;

  /**
   * Define a protocol template, or version an existing one
   *
   * `POST /protocol-templates` — `protocol/define-template`
   */
  protocolDefineTemplate(input: { key: string; title: string; content: unknown }): Promise<ProtocolTemplateRow>;

  /**
   * Record a response on an open checklist protocol (append-only)
   *
   * `POST /protocols/{instanceId}/responses` — `protocol/fill`
   */
  protocolFill(input: { instanceId: string; itemKey: string; value: boolean | string; note?: string }): Promise<ProtocolResponse>;

  /**
   * One protocol with its template, responses, signatures and requests
   *
   * `GET /protocols/{instanceId}` — `protocol/get`
   */
  protocolGet(input: { instanceId: string }): Promise<{ instance: ProtocolInstance; template: { key: string; version: number; title: string; content: { kind: "checklist"; sections: ({ title: string; items: ({ key: string; label: string; type: "check" | "value" | "text"; unit?: string })[] })[] } | { kind: "document"; documentType: string; hashRecipe: string; description?: string } }; responses: ProtocolResponse[]; latest: Record<string, ProtocolResponse>; signature: ProtocolSignature | null; signatures: ProtocolSignature[]; requests: ProtocolSignatureRequest[] }>;

  /**
   * The latest version of every template — the instantiation picker
   *
   * `GET /protocol-templates` — `protocol/list-templates`
   */
  protocolListTemplates(): Promise<ProtocolTemplateRow[]>;

  /**
   * Sign a protocol in-app — freezes its content forever
   *
   * `POST /protocols/{instanceId}/sign` — `protocol/sign`
   */
  protocolSign(input: { instanceId: string }): Promise<{ instance: ProtocolInstance; signature: ProtocolSignature }>;

  /**
   * Void (supersede) a protocol — never deletes
   *
   * `POST /protocols/{instanceId}/void` — `protocol/void`
   */
  protocolVoid(input: { instanceId: string; reason: string }): Promise<ProtocolInstance>;

  /**
   * Assign a technician
   *
   * `POST /workorders/{orderId}/assign` — `workorder/assign`
   */
  workorderAssign(input: { orderId: string; technician: string }): Promise<WorkOrder>;

  /**
   * Close the order at hand-over
   *
   * `POST /workorders/{orderId}/close` — `workorder/close`
   */
  workorderClose(input: { orderId: string }): Promise<WorkOrder>;

  /**
   * One work order with everything reported against it
   *
   * `GET /workorders/{orderId}` — `workorder/get`
   */
  workorderGet(input: { orderId: string }): Promise<{ order: WorkOrder; time: ({ id: string; order_id: string; technician: string; hours: string; note: string | null; reported_at: string })[]; material: MaterialLine[] }>;

  /**
   * Work orders, optionally filtered by status
   *
   * `GET /workorders` — `workorder/list`
   */
  workorderList(input: { status?: string }): Promise<WorkOrder[]>;

  /**
   * Report material against the order
   *
   * `POST /workorders/{orderId}/material` — `workorder/report-material`
   */
  workorderReportMaterial(input: { orderId: string; article: string; qty: string; note?: string }): Promise<MaterialLine>;

  /**
   * Report time against the order
   *
   * `POST /workorders/{orderId}/time` — `workorder/report-time`
   */
  workorderReportTime(input: { orderId: string; hours: string; note?: string }): Promise<{ id: string; order_id: string; technician: string; hours: string; note: string | null; reported_at: string }>;

  /**
   * Start the work
   *
   * `POST /workorders/{orderId}/start` — `workorder/start`
   */
  workorderStart(input: { orderId: string }): Promise<WorkOrder>;
}

/**
 * The plumbing below is deliberately untyped against the interface above, and cast
 * once at the end.
 *
 * `send` cannot know an operation's return type — it has a `Response`, not a schema
 * — so every method would otherwise need its own `as` and the file would carry
 * fourteen casts instead of one. The interface is what a caller sees, and it IS
 * derived from the model; this is the seam where a runtime that speaks `unknown`
 * meets it.
 */
type Args = Record<string, unknown>;

const omit = (input: Record<string, unknown>, keys: string[]): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(input ?? {})) if (!keys.includes(k)) out[k] = v;
  return out;
};

/** Declared fields become a query string; `undefined` is absent rather than the string "undefined". */
const query = (values: Record<string, unknown> | undefined): string => {
  if (!values) return '';
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(values)) {
    if (v === undefined || v === null) continue;
    params.set(k, String(v));
  }
  const s = params.toString();
  return s ? `?${s}` : '';
};

export function createClient(options: ClientOptions = {}): CalloutClient {
  const baseUrl = options.baseUrl ?? '/api';
  const doFetch = options.fetch ?? globalThis.fetch.bind(globalThis);
  const readMessage = options.errorMessage ?? defaultErrorMessage;

  /** One request, against a path that is ALREADY prefixed and query-stringed. */
  const raw = async (fullPath: string, method: string, body: unknown): Promise<Response> => {
    const hasBody = body !== undefined && method !== 'GET' && method !== 'DELETE';
    return await doFetch(fullPath, {
      method,
      headers: {
        ...(hasBody ? { 'content-type': 'application/json' } : {}),
        ...(options.headers?.() ?? {}),
      },
      ...(hasBody ? { body: JSON.stringify(body) } : {}),
    });
  };

  const parse = async (res: Response): Promise<unknown> => {
    const text = await res.text();
    const body: unknown = text ? JSON.parse(text) : null;
    if (!res.ok) throw new ApiError(res.status, readMessage(body, res) ?? res.statusText, body);
    return body;
  };

  const send = async (path: string, method: string, body: unknown, params: unknown): Promise<unknown> =>
    await parse(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  return {
    completeWorkorder: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.orderId))}/complete`, "POST", omit(input, ["orderId"]), undefined),
    createCustomer: (input: Args) =>
      send("/customers", "POST", input, undefined),
    createFacility: (input: Args) =>
      send(`/customers/${encodeURIComponent(String(input.customerId))}/facilities`, "POST", omit(input, ["customerId"]), undefined),
    createWorkorder: (input: Args) =>
      send("/workorders", "POST", input, undefined),
    instantiateProtocol: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.entityId))}/protocols`, "POST", omit(input, ["entityId"]), undefined),
    listCustomers: () =>
      send("/customers", "GET", undefined, undefined),
    portalOrders: () =>
      send("/portal/orders", "GET", undefined, undefined),
    priceList: () =>
      send("/prices", "GET", undefined, undefined),
    searchCustomers: (input: Args) =>
      send("/customers/search", "GET", undefined, input),
    upsertPrice: (input: Args) =>
      send("/prices", "POST", input, undefined),
    invoicingExport: (input: Args) =>
      send(`/invoicing/${encodeURIComponent(String(input.underlagId))}/export`, "POST", omit(input, ["underlagId"]), undefined),
    invoicingGet: (input: Args) =>
      send(`/invoicing/${encodeURIComponent(String(input.underlagId))}`, "GET", undefined, omit(input, ["underlagId"])),
    invoicingList: (input: Args) =>
      send("/invoicing", "GET", undefined, input),
    protocolDefineTemplate: (input: Args) =>
      send("/protocol-templates", "POST", input, undefined),
    protocolFill: (input: Args) =>
      send(`/protocols/${encodeURIComponent(String(input.instanceId))}/responses`, "POST", omit(input, ["instanceId"]), undefined),
    protocolGet: (input: Args) =>
      send(`/protocols/${encodeURIComponent(String(input.instanceId))}`, "GET", undefined, omit(input, ["instanceId"])),
    protocolListTemplates: () =>
      send("/protocol-templates", "GET", undefined, undefined),
    protocolSign: (input: Args) =>
      send(`/protocols/${encodeURIComponent(String(input.instanceId))}/sign`, "POST", omit(input, ["instanceId"]), undefined),
    protocolVoid: (input: Args) =>
      send(`/protocols/${encodeURIComponent(String(input.instanceId))}/void`, "POST", omit(input, ["instanceId"]), undefined),
    workorderAssign: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.orderId))}/assign`, "POST", omit(input, ["orderId"]), undefined),
    workorderClose: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.orderId))}/close`, "POST", omit(input, ["orderId"]), undefined),
    workorderGet: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.orderId))}`, "GET", undefined, omit(input, ["orderId"])),
    workorderList: (input: Args) =>
      send("/workorders", "GET", undefined, input),
    workorderReportMaterial: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.orderId))}/material`, "POST", omit(input, ["orderId"]), undefined),
    workorderReportTime: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.orderId))}/time`, "POST", omit(input, ["orderId"]), undefined),
    workorderStart: (input: Args) =>
      send(`/workorders/${encodeURIComponent(String(input.orderId))}/start`, "POST", omit(input, ["orderId"]), undefined),
  } as unknown as CalloutClient;
}
