/**
 * GENERATED by scripts/update-rate-card.mjs — DO NOT EDIT.
 *
 * Regenerate: pnpm --filter @substrat-run/builder update-rate-card
 * (review the diff — this file is the billing checkpoint, builder-harness.md §2.2).
 *
 * Sources cross-checked at generation: models.dev api.json × LiteLLM
 * model_prices_and_context_window.json (both MIT). Rates are provider LIST
 * prices in USD per 1M tokens, decimal strings. Tier selection is
 * all-or-nothing by the request's total input tokens (DashScope/Anthropic
 * threshold semantics — the whole request bills at the tier it lands in).
 */
import type { ModelRate } from './pricing.js';

export const RATE_CARD_GENERATED_AT = '2026-08-15';

export const RATE_CARD: readonly ModelRate[] = [
	{
		"provider": "qwen",
		"idPrefix": "qwen3.6-flash",
		"label": "Qwen 3.6 Flash",
		"contextTokens": 1000000,
		"tiers": [
			{
				"upToInputTokens": null,
				"inputPer1M": "0.1875",
				"outputPer1M": "1.125",
				"cacheReadPer1M": null,
				"cacheWritePer1M": "0.234375"
			}
		],
		"sources": [
			"models.dev:alibaba/qwen3.6-flash"
		]
	},
	{
		"provider": "qwen",
		"idPrefix": "qwen3.8-max",
		"label": "Qwen 3.8 Max",
		"contextTokens": 991808,
		"tiers": [
			{
				"upToInputTokens": null,
				"inputPer1M": "2",
				"outputPer1M": "6",
				"cacheReadPer1M": "0.25",
				"cacheWritePer1M": "2.5"
			}
		],
		"sources": [
			"models.dev:alibaba/qwen3.8-max",
			"litellm:dashscope/qwen3.8-max",
			"https://www.alibabacloud.com/help/en/model-studio/models"
		]
	},
	{
		"provider": "anthropic",
		"idPrefix": "claude-sonnet-5",
		"label": "Claude Sonnet 5",
		"contextTokens": 1000000,
		"tiers": [
			{
				"upToInputTokens": null,
				"inputPer1M": "2",
				"outputPer1M": "10",
				"cacheReadPer1M": "0.2",
				"cacheWritePer1M": "2.5"
			}
		],
		"sources": [
			"models.dev:anthropic/claude-sonnet-5",
			"litellm:claude-sonnet-5"
		]
	},
	{
		"provider": "anthropic",
		"idPrefix": "claude-opus-5",
		"label": "Claude Opus 5",
		"contextTokens": 1000000,
		"tiers": [
			{
				"upToInputTokens": null,
				"inputPer1M": "5",
				"outputPer1M": "25",
				"cacheReadPer1M": "0.5",
				"cacheWritePer1M": "6.25"
			}
		],
		"sources": [
			"models.dev:anthropic/claude-opus-5",
			"litellm:claude-opus-5"
		]
	}
];
