// GENERATED by tools/client-emit.mts from spec/model.ts — do not edit by hand.
//
// Re-emit with `pnpm lint:client`; CI runs `pnpm lint:client --check` and fails on
// drift, so the client cannot fall behind the model the way a hand-written one did.
//
// Standalone on purpose: no imports, so the browser bundle carries no schema library
// and `tools/declared-deps.mjs` has nothing to object to.

/** A failed request. `status` is the interesting field — 403 is the permission model answering. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
    readonly body: unknown,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

/**
 * One page of a paged read, reassembled from the response.
 *
 * The BODY is the entries and always was; the walk rides in headers (#829), which is
 * what let paging be adopted without renaming a live endpoint's response. This puts
 * the two back together so a caller sees a page rather than a header protocol.
 *
 * `next` is an absolute URL to FOLLOW (RFC 8288), not a cursor to reassemble — this
 * request's filters and page size travel with it. Its absence is how the walk ends.
 */
export interface Paged<T> {
  entries: T[];
  /** Hand back to `follow()`. `null` when there is no next page. */
  next: string | null;
  /** From `X-Total-Count`, and only for a read that declares `total`. */
  total: number | null;
}

export interface ClientOptions {
  /** Prefixed to every declared path. Matches `mountOperations`' own default. */
  baseUrl?: string;
  /** Per-request headers — an auth token, or this demo's `x-principal` persona seam. */
  headers?: () => Record<string, string>;
  /** Injectable so the client works under a test harness, not only in a browser. */
  fetch?: typeof globalThis.fetch;
  /**
   * Pull a message out of an error body.
   *
   * The one thing here the model does NOT declare: a vertical picks its error
   * envelope in its own `app.onError`, so this is a best effort over the shapes in
   * use — `{ error }`, and problem+json's `detail`/`title` — and an app that
   * answers something else says so here rather than being guessed at.
   */
  errorMessage?: (body: unknown, response: Response) => string | undefined;
}

function defaultErrorMessage(body: unknown): string | undefined {
  if (typeof body !== 'object' || body === null) return undefined;
  const b = body as Record<string, unknown>;
  for (const key of ['error', 'detail', 'title', 'message']) {
    if (typeof b[key] === 'string') return b[key] as string;
  }
  return undefined;
}


/** `todo_owners` — declared in spec/model.ts. */
export interface Owner {
  id: string;
  email: string;
  display_name: string;
  created_at: string;
}

/** `todo_lists` — declared in spec/model.ts. */
export interface List {
  id: string;
  owner_id: string;
  name: string;
  created_at: string;
}

/** `todo_items` — declared in spec/model.ts. */
export interface Item {
  id: string;
  list_id: string;
  text: string;
  done: number;
  added_by: string;
  created_at: string;
}

/** `todo_shares` — declared in spec/model.ts. */
export interface Share {
  id: string;
  list_id: string;
  principal: string;
  email: string;
  created_at: string;
}

/** Every operation this vertical binds to HTTP, one method each. */
export interface TodoClient {
  /**
   * Add an item to a list
   *
   * `POST /lists/{listId}/items` — `todo/add-item`
   */
  addItem(input: { listId: string; text: string }): Promise<Item>;

  /**
   * Create a list
   *
   * `POST /lists` — `todo/create-list`
   */
  createList(input: { name: string }): Promise<List>;

  /**
   * Delete an item
   *
   * `DELETE /items/{itemId}` — `todo/delete-item`
   */
  deleteItem(input: { itemId: string }): Promise<{ id: string; deleted: boolean }>;

  /**
   * Delete a list and everything on it
   *
   * `DELETE /lists/{listId}` — `todo/delete-list`
   */
  deleteList(input: { listId: string }): Promise<{ id: string; deleted: boolean }>;

  /**
   * Claim your account in this workspace
   *
   * `POST /join` — `todo/join`
   */
  join(input: { email: string; displayName: string }): Promise<Owner>;

  /**
   * The items on a list
   *
   * `GET /lists/{listId}/items` — `todo/list-items`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listItems(input: { listId: string; limit?: number; cursor?: string }): Promise<Paged<Item>>;

  /**
   * Who this list is shared with
   *
   * `GET /lists/{listId}/shares` — `todo/list-shares`
   */
  listShares(input: { listId: string }): Promise<Share[]>;

  /**
   * List the lists you own or have been shared
   *
   * `GET /lists` — `todo/my-lists`
   */
  myLists(): Promise<List[]>;

  /**
   * Rename a list
   *
   * `PATCH /lists/{listId}` — `todo/rename-list`
   */
  renameList(input: { listId: string; name: string }): Promise<List>;

  /**
   * Revoke someone’s access to a list
   *
   * `DELETE /shares/{shareId}` — `todo/revoke-share`
   */
  revokeShare(input: { shareId: string }): Promise<{ id: string; revoked: boolean }>;

  /**
   * Find items across the lists you can see
   *
   * `GET /items/search` — `todo/search-items`
   */
  searchItems(input: { q: string; limit?: number }): Promise<{ results: Item[]; limit: number; capped: boolean }>;

  /**
   * Find items on a list by text
   *
   * `GET /lists/{listId}/items/search` — `todo/search-list-items`
   */
  searchListItems(input: { listId: string; q: string; limit?: number }): Promise<{ results: Item[]; limit: number; capped: boolean }>;

  /**
   * Tick an item off, or put it back
   *
   * `POST /items/{itemId}/done` — `todo/set-item-done`
   */
  setItemDone(input: { itemId: string; done: boolean }): Promise<Item>;

  /**
   * Share a list with someone by email
   *
   * `POST /lists/{listId}/shares` — `todo/share-list`
   */
  shareList(input: { listId: string; email: string }): Promise<Share>;

  /**
   * Fetch the next page of any paged read, given a previous page's `next`.
   *
   * One method for every paged read rather than one per read: `next` is a URL that
   * already carries the filters, so there is nothing left for a caller to restate.
   */
  follow<T>(next: string): Promise<Paged<T>>;
}

/**
 * The plumbing below is deliberately untyped against the interface above, and cast
 * once at the end.
 *
 * `send` cannot know an operation's return type — it has a `Response`, not a schema
 * — so every method would otherwise need its own `as` and the file would carry
 * fourteen casts instead of one. The interface is what a caller sees, and it IS
 * derived from the model; this is the seam where a runtime that speaks `unknown`
 * meets it.
 */
type Args = Record<string, unknown>;

const omit = (input: Record<string, unknown>, keys: string[]): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(input ?? {})) if (!keys.includes(k)) out[k] = v;
  return out;
};

/** Declared fields become a query string; `undefined` is absent rather than the string "undefined". */
const query = (values: Record<string, unknown> | undefined): string => {
  if (!values) return '';
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(values)) {
    if (v === undefined || v === null) continue;
    params.set(k, String(v));
  }
  const s = params.toString();
  return s ? `?${s}` : '';
};

/**
 * The `rel="next"` URL out of an RFC 8288 `Link` header, or null.
 *
 * Only `next` is looked for because only `next` is sent: keyset paging walks one
 * way and does not know its own offset, so there is no `prev`, `first` or `last`
 * to honour. A header naming some other relation is not this walk's.
 */
const nextFrom = (header: string | null): string | null => {
  if (!header) return null;
  for (const part of header.split(',')) {
    const match = /^\s*<([^>]+)>\s*;\s*(.+)$/.exec(part);
    if (match && /rel\s*=\s*"?next"?/.test(match[2] as string)) return match[1] as string;
  }
  return null;
};

export function createClient(options: ClientOptions = {}): TodoClient {
  const baseUrl = options.baseUrl ?? '/api';
  const doFetch = options.fetch ?? globalThis.fetch.bind(globalThis);
  const readMessage = options.errorMessage ?? defaultErrorMessage;

  /** One request, against a path that is ALREADY prefixed and query-stringed. */
  const raw = async (fullPath: string, method: string, body: unknown): Promise<Response> => {
    const hasBody = body !== undefined && method !== 'GET' && method !== 'DELETE';
    return await doFetch(fullPath, {
      method,
      headers: {
        ...(hasBody ? { 'content-type': 'application/json' } : {}),
        ...(options.headers?.() ?? {}),
      },
      ...(hasBody ? { body: JSON.stringify(body) } : {}),
    });
  };

  const parse = async (res: Response): Promise<unknown> => {
    const text = await res.text();
    const body: unknown = text ? JSON.parse(text) : null;
    if (!res.ok) throw new ApiError(res.status, readMessage(body, res) ?? res.statusText, body);
    return body;
  };

  const send = async (path: string, method: string, body: unknown, params: unknown): Promise<unknown> =>
    await parse(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  /**
   * A paged read: the entries come from the body, the walk from the headers.
   *
   * A cross-origin caller reads neither header without `Access-Control-Expose-Headers`,
   * and the symptom is not an error — it is a list that looks like it has one page. Under
   * a same-origin dev proxy (this demo) or a same-origin deployment, both are readable.
   */
  const readPage = async (res: Response): Promise<Paged<unknown>> => {
    const entries = (await parse(res)) as unknown[];
    const total = res.headers.get('X-Total-Count');
    return { entries, next: nextFrom(res.headers.get('Link')), total: total === null ? null : Number(total) };
  };

  const page = async (path: string, method: string, body: unknown, params: unknown): Promise<Paged<unknown>> =>
    await readPage(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  return {
    addItem: (input: Args) =>
      send(`/lists/${encodeURIComponent(String(input.listId))}/items`, "POST", omit(input, ["listId"]), undefined),
    createList: (input: Args) =>
      send("/lists", "POST", input, undefined),
    deleteItem: (input: Args) =>
      send(`/items/${encodeURIComponent(String(input.itemId))}`, "DELETE", undefined, omit(input, ["itemId"])),
    deleteList: (input: Args) =>
      send(`/lists/${encodeURIComponent(String(input.listId))}`, "DELETE", undefined, omit(input, ["listId"])),
    join: (input: Args) =>
      send("/join", "POST", input, undefined),
    listItems: (input: Args) =>
      page(`/lists/${encodeURIComponent(String(input.listId))}/items`, "GET", undefined, omit(input, ["listId"])),
    listShares: (input: Args) =>
      send(`/lists/${encodeURIComponent(String(input.listId))}/shares`, "GET", undefined, omit(input, ["listId"])),
    myLists: () =>
      send("/lists", "GET", undefined, undefined),
    renameList: (input: Args) =>
      send(`/lists/${encodeURIComponent(String(input.listId))}`, "PATCH", omit(input, ["listId"]), undefined),
    revokeShare: (input: Args) =>
      send(`/shares/${encodeURIComponent(String(input.shareId))}`, "DELETE", undefined, omit(input, ["shareId"])),
    searchItems: (input: Args) =>
      send("/items/search", "GET", undefined, input),
    searchListItems: (input: Args) =>
      send(`/lists/${encodeURIComponent(String(input.listId))}/items/search`, "GET", undefined, omit(input, ["listId"])),
    setItemDone: (input: Args) =>
      send(`/items/${encodeURIComponent(String(input.itemId))}/done`, "POST", omit(input, ["itemId"]), undefined),
    shareList: (input: Args) =>
      send(`/lists/${encodeURIComponent(String(input.listId))}/shares`, "POST", omit(input, ["listId"]), undefined),
    follow: async (next: string) => {
      // The link names the API's OWN origin, which under a dev proxy is not the origin
      // this page was served from. So the path is kept and the origin is taken from
      // whatever this client was configured to talk to: relative for a browser, which
      // keeps the request same-origin, absolute for a harness that has no page.
      const link = new URL(next, 'http://substrat.invalid');
      const target = /^https?:\/\//.test(baseUrl)
        ? new URL(link.pathname + link.search, baseUrl).href
        : link.pathname + link.search;
      return await readPage(await raw(target, 'GET', undefined));
    },
  } as unknown as TodoClient;
}
