// Regenerate the vendored Public Suffix List data (`../src/data.ts`) from the
// canonical source. Run when refreshing the list:
//
//   node packages/psl/scripts/build-data.mjs
//
// The list is intentionally VENDORED (checked in), not fetched at runtime: module
// code and Workers have no network, and a cookie-safety guard must never depend on a
// live download. Refreshing is a reviewable diff, like any other checked-in data.
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'https://publicsuffix.org/list/public_suffix_list.dat';
const src = process.argv[2] ?? '/tmp/psl.dat';
const raw = readFileSync(src, 'utf8');
const version = (raw.match(/VERSION: (.*)/) || [])[1]?.trim() || 'unknown';

const rules = [];
for (let line of raw.split('\n')) {
  line = line.trim();
  if (!line || line.startsWith('//')) continue; // comments + blanks
  rules.push(line.toLowerCase());
}
const uniq = Array.from(new Set(rules)).sort();
const data = uniq.join('\n');

// A remote source cannot be re-emitted hermetically in CI, so this file carries a
// GENERATED_AT stamp in place of a `--check` gate (CLAUDE.md, "Generated files carry
// three marks"). The stamp is the refresh date; the PSL's own VERSION line beside it
// says which list that refresh vendored.
const generatedAt = new Date().toISOString().slice(0, 10);
const out = `// GENERATED by packages/psl/scripts/build-data.mjs from ${SOURCE} — do not edit by hand.
// GENERATED_AT: ${generatedAt}
// ${uniq.length} rules (ICANN + PRIVATE sections). PSL VERSION: ${version}
// Regenerate: node packages/psl/scripts/build-data.mjs
//
// One rule per line. A leading '*' is a wildcard label; a leading '!' is an exception
// rule. The matching algorithm lives in ./list.ts (the canonical PSL algorithm).
export const PSL_VERSION = ${JSON.stringify(version)};
export const PSL_RULES = ${JSON.stringify(data)};
`;
writeFileSync(new URL('../src/data.ts', import.meta.url), out);
console.log(`wrote ${uniq.length} rules (${data.length} bytes), version ${version}`);
