#!/usr/bin/env node
// Generate src/assets.generated.ts from the built SPA (app/dist).
//
// A sandbox-clean, CP-less vertical (scope-local-permissions.md Phase 3) is pushed into
// the WfP dispatch namespace as a worker bundle. Static assets are NOT a binding there —
// Cloudflare uploads them through a separate blake3 upload-session — so instead of that
// protocol, the demo's small SPA rides along as ordinary worker MODULES: this script
// inlines every file under app/dist into one generated module the worker serves from
// (see src/assets.ts). Reuses the module-upload path `substrat push` already has.
//
// Run automatically before typecheck (empty map if app/dist is absent — keeps CI green)
// and after the app build in cf:dry-run / cf:deploy (real content for the deploy).
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
// (idempotent write helper defined below — only rewrites when content changed, so the
//  wrangler `build` watcher doesn't loop on its own output during `wrangler dev`.)
import { join, relative, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const distDir = join(here, '..', 'app', 'dist');
const outFile = join(here, '..', 'src', 'assets.generated.ts');

// Text types inline as UTF-8 string literals (readable diffs, no decode cost); everything
// else (fonts, images) inlines as base64 and is decoded at serve time.
const TEXT_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.webmanifest': 'application/manifest+json',
};
const BINARY_TYPES = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
};

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const entries = [];

// The Scalar API Reference renderer, self-hosted (design/api-surface.md §2.3):
// /api/docs must never load its renderer from a CDN, so the pinned package's
// standalone bundle rides the same inline-asset path as the SPA. Resolved via
// the package's node_modules dir (its `exports` map does not expose dist/).
const scalarJs = join(here, '..', 'node_modules', '@scalar', 'api-reference', 'dist', 'browser', 'standalone.js');
if (existsSync(scalarJs)) {
  entries.push(
    `  "/assets/scalar-api-reference.js": { body: ${JSON.stringify(readFileSync(scalarJs, 'utf8'))}, encoding: 'utf8', type: 'text/javascript; charset=utf-8' },`,
  );
} else {
  console.warn('gen-assets: @scalar/api-reference not installed — /api/docs will 404 its renderer');
}

if (existsSync(distDir)) {
  for (const file of walk(distDir)) {
    const ext = extname(file).toLowerCase();
    const urlPath = '/' + relative(distDir, file).split('\\').join('/');
    if (TEXT_TYPES[ext]) {
      const body = readFileSync(file, 'utf8');
      entries.push(`  ${JSON.stringify(urlPath)}: { body: ${JSON.stringify(body)}, encoding: 'utf8', type: ${JSON.stringify(TEXT_TYPES[ext])} },`);
    } else {
      const body = readFileSync(file).toString('base64');
      const type = BINARY_TYPES[ext] ?? 'application/octet-stream';
      entries.push(`  ${JSON.stringify(urlPath)}: { body: ${JSON.stringify(body)}, encoding: 'base64', type: ${JSON.stringify(type)} },`);
    }
  }
}

const header = `// GENERATED by scripts/gen-assets.mjs from app/dist — DO NOT EDIT, and do not commit.
// The built SPA, inlined so the pushed worker serves its own UI without an ASSETS
// binding (WfP static assets are a separate upload path). Regenerate with 'pnpm gen:assets'.
export interface BundledAsset { body: string; encoding: 'utf8' | 'base64'; type: string; }
export const ASSETS: Record<string, BundledAsset> = {
`;

const next = header + entries.join('\n') + (entries.length ? '\n' : '') + '};\n';
// Only write when the content actually changed. `wrangler dev` runs this via the build
// hook and watches src/ — rewriting an identical file on every build would retrigger the
// watcher and loop forever. A no-op write when unchanged breaks that cycle.
const prev = existsSync(outFile) ? readFileSync(outFile, 'utf8') : null;
if (prev === next) {
  console.log(`gen-assets: ${entries.length} asset(s) unchanged — src/assets.generated.ts left as-is`);
} else {
  writeFileSync(outFile, next);
  console.log(`gen-assets: wrote ${entries.length} asset(s) → src/assets.generated.ts`);
}
