/**
 * GENERATED by tools/emit-migrations.mts from journal.json — do not edit by hand.
 *
 * The journal is the record; this is the shape the kernel registers. Append a
 * migration by changing spec/model.ts and re-running:
 *
 *     pnpm --filter @substrat-run/demo-tock emit:migrations
 *
 * CI re-emits with --check and fails on drift, so a hand-edit to shipped SQL is
 * caught here rather than at the next deploy.
 */
import type { SqlMigration } from '@substrat-run/kernel';

export const tockMigrations: SqlMigration[] = [
  {
    // add-tock_field_history-and-10-more
    version: '0001',
    sql: `
      CREATE TABLE tock_field_history (
        source_key TEXT NOT NULL,
        field TEXT NOT NULL,
        day TEXT NOT NULL,
        first_seen TEXT NOT NULL,
        last_seen TEXT NOT NULL,
        n INTEGER NOT NULL,
        PRIMARY KEY (source_key, field, day)
      );

      CREATE TABLE tock_labels (
        run_id TEXT NOT NULL,
        dim TEXT NOT NULL,
        value TEXT NOT NULL,
        label TEXT NOT NULL,
        captured_at TEXT NOT NULL,
        PRIMARY KEY (run_id, dim, value)
      );

      CREATE TABLE tock_observations (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        field TEXT NOT NULL,
        present_count INTEGER NOT NULL,
        null_count INTEGER NOT NULL,
        inferred_type TEXT NOT NULL,
        distinct_estimate INTEGER NOT NULL,
        declared INTEGER NOT NULL,
        UNIQUE (run_id, field)
      );

      CREATE TABLE tock_rollups (
        source_key TEXT NOT NULL,
        grain TEXT NOT NULL,
        dim_set TEXT NOT NULL,
        period_start TEXT NOT NULL,
        dim1 TEXT NOT NULL,
        dim2 TEXT NOT NULL,
        run_id TEXT NOT NULL,
        events INTEGER NOT NULL,
        measure TEXT,
        unit TEXT,
        PRIMARY KEY (source_key, grain, dim_set, period_start, dim1, dim2, run_id)
      );

      CREATE TABLE tock_rows (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        occurred_at TEXT NOT NULL,
        subject_key TEXT NOT NULL,
        dims_json TEXT NOT NULL,
        metrics_json TEXT NOT NULL
      );

      CREATE TABLE tock_rule_states (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        rule_kind TEXT NOT NULL CHECK (rule_kind IN ('bot_list','threshold','dedup_window','salt')),
        identifier TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        captured_at TEXT NOT NULL,
        UNIQUE (run_id, rule_kind)
      );

      CREATE TABLE tock_runs (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        schema_version INTEGER,
        filename TEXT NOT NULL,
        byte_size INTEGER NOT NULL,
        content_hash TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('received','profiled','mapped','counted','failed')),
        period_from TEXT NOT NULL,
        period_to TEXT NOT NULL,
        row_count INTEGER,
        rejected_count INTEGER,
        received_at TEXT NOT NULL,
        received_by TEXT NOT NULL,
        counted_at TEXT
      );

      CREATE TABLE tock_salts (
        day TEXT PRIMARY KEY NOT NULL,
        salt_id TEXT NOT NULL,
        secret TEXT,
        created_at TEXT NOT NULL,
        destroyed_at TEXT
      );

      CREATE TABLE tock_schemas (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        version INTEGER NOT NULL,
        fields_json TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (source_key, version)
      );

      CREATE TABLE tock_source_files (
        run_id TEXT PRIMARY KEY NOT NULL REFERENCES tock_runs(id),
        content_hash TEXT NOT NULL,
        byte_size INTEGER NOT NULL,
        storage_key TEXT NOT NULL,
        stored_at TEXT NOT NULL,
        purge_after TEXT NOT NULL
      );

      CREATE TABLE tock_sources (
        key TEXT PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        expected_cadence TEXT NOT NULL,
        created_at TEXT NOT NULL
      );
    `,
  },
  {
    // add-tock_runs-format-and-3-more
    version: '0002',
    sql: `
      ALTER TABLE tock_runs ADD COLUMN format TEXT CHECK (format IN ('csv','jsonl'));

      ALTER TABLE tock_runs ADD COLUMN delimiter TEXT;

      ALTER TABLE tock_runs ADD COLUMN time_field TEXT;

      ALTER TABLE tock_runs ADD COLUMN subject_field TEXT;
    `,
  },
  {
    // variant-key-rebuild
    version: '0003',
    sql: `
      -- HAND-WRITTEN. The planner refuses to generate this and is right to: SQLite cannot add a
      -- UNIQUE constraint to a table that exists, so both tables are rebuilt the long way round.
      --
      -- Every backfilled value is '' and every one of them is TRUE, which is what makes a default
      -- honest here where it would not have been for the read plan in 0002. An existing schema
      -- described every record of its source, and the empty variant IS the envelope every record
      -- carries. An existing row matched no variant because none had been declared, and the empty
      -- variant is exactly how "matched none" is spelled. Neither backfill invents a choice.

      CREATE TABLE tock_observations_new (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        variant_key TEXT NOT NULL,
        field TEXT NOT NULL,
        present_count INTEGER NOT NULL,
        null_count INTEGER NOT NULL,
        inferred_type TEXT NOT NULL,
        distinct_estimate INTEGER NOT NULL,
        declared INTEGER NOT NULL,
        UNIQUE (run_id, variant_key, field)
      );

      INSERT INTO tock_observations_new
        (id, run_id, variant_key, field, present_count, null_count, inferred_type, distinct_estimate, declared)
        SELECT id, run_id, '', field, present_count, null_count, inferred_type, distinct_estimate, declared
          FROM tock_observations;

      DROP TABLE tock_observations;

      ALTER TABLE tock_observations_new RENAME TO tock_observations;

      CREATE TABLE tock_schemas_new (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        variant_key TEXT NOT NULL,
        version INTEGER NOT NULL,
        fields_json TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (source_key, variant_key, version)
      );

      INSERT INTO tock_schemas_new
        (id, source_key, variant_key, version, fields_json, created_by, created_at)
        SELECT id, source_key, '', version, fields_json, created_by, created_at FROM tock_schemas;

      DROP TABLE tock_schemas;

      ALTER TABLE tock_schemas_new RENAME TO tock_schemas;

      ALTER TABLE tock_rows ADD COLUMN variant_key TEXT NOT NULL DEFAULT '';

    `,
  },
  {
    // add-tock_sources-discriminators-and-1-more
    version: '0004',
    sql: `
      ALTER TABLE tock_sources ADD COLUMN discriminators TEXT;

      CREATE TABLE tock_variants (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        key TEXT NOT NULL,
        selector TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (source_key, key)
      );
    `,
  },
  {
    // rollup-output-key
    version: '0005',
    sql: `
      -- HAND-WRITTEN, for the reason 0003 was: SQLite cannot change a primary key in place, so
      -- the table is rebuilt the long way round.
      --
      -- The backfill is '' and it is TRUE: these rows were counted before output shapes existed,
      -- against the envelope directly, and '' is exactly how "no output shape" is spelled. As in
      -- 0003 and unlike 0002, a default here records what happened rather than inventing a choice.
      --
      -- output_key goes SECOND in the key, straight after the source. The report still asks for
      -- one source, one output, one grain, one grouping and a date RANGE, so the range has to stay
      -- a key prefix — putting the new column after period_start would have turned every report
      -- back into a scan of the whole grouping.

      CREATE TABLE tock_rollups_new (
        source_key TEXT NOT NULL,
        output_key TEXT NOT NULL,
        grain TEXT NOT NULL,
        dim_set TEXT NOT NULL,
        period_start TEXT NOT NULL,
        dim1 TEXT NOT NULL,
        dim2 TEXT NOT NULL,
        run_id TEXT NOT NULL,
        events INTEGER NOT NULL,
        measure TEXT,
        unit TEXT,
        PRIMARY KEY (source_key, output_key, grain, dim_set, period_start, dim1, dim2, run_id)
      );

      INSERT INTO tock_rollups_new
        (source_key, output_key, grain, dim_set, period_start, dim1, dim2, run_id, events, measure, unit)
        SELECT source_key, '', grain, dim_set, period_start, dim1, dim2, run_id, events, measure, unit
          FROM tock_rollups;

      DROP TABLE tock_rollups;

      ALTER TABLE tock_rollups_new RENAME TO tock_rollups;

    `,
  },
  {
    // add-tock_mappings-and-1-more
    version: '0006',
    sql: `
      CREATE TABLE tock_mappings (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        variant_key TEXT NOT NULL,
        output_key TEXT NOT NULL,
        version INTEGER NOT NULL,
        rules_json TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (source_key, variant_key, output_key, version)
      );

      CREATE TABLE tock_output_schemas (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        key TEXT NOT NULL,
        version INTEGER NOT NULL,
        fields_json TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (source_key, key, version)
      );
    `,
  },
  {
    // rule-kind-mapping
    version: '0007',
    sql: `
      -- HAND-WRITTEN. Widening an enum in the model does not widen the CHECK constraint the
      -- table already carries, and SQLite cannot alter one in place — so the table is rebuilt.
      --
      -- Worth knowing WHY this needed writing by hand: the planner does not diff CHECK constraints,
      -- so the model said five rule kinds while the table enforced four and nothing was red. It
      -- surfaced as a failing insert at count time, which is a long way from the declaration that
      -- caused it. Any future enum widening on a shipped table has the same shape.

      CREATE TABLE tock_rule_states_new (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        rule_kind TEXT NOT NULL CHECK (rule_kind IN ('bot_list','threshold','dedup_window','salt','mapping')),
        identifier TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        captured_at TEXT NOT NULL,
        UNIQUE (run_id, rule_kind)
      );

      INSERT INTO tock_rule_states_new (id, run_id, rule_kind, identifier, content_hash, captured_at)
        SELECT id, run_id, rule_kind, identifier, content_hash, captured_at FROM tock_rule_states;

      DROP TABLE tock_rule_states;

      ALTER TABLE tock_rule_states_new RENAME TO tock_rule_states;

    `,
  },
];
