/**
 * GENERATED by tools/emit-migrations.mts from journal.json — do not edit by hand.
 *
 * The journal is the record; this is the shape the kernel registers. Append a
 * migration by changing spec/model.ts and re-running:
 *
 *     pnpm --filter @substrat-run/demo-tock emit:migrations
 *
 * CI re-emits with --check and fails on drift, so a hand-edit to shipped SQL is
 * caught here rather than at the next deploy.
 */
import type { SqlMigration } from '@substrat-run/kernel';

export const tockMigrations: SqlMigration[] = [
  {
    // add-tock_field_history-and-10-more
    version: '0001',
    sql: `
      CREATE TABLE tock_field_history (
        source_key TEXT NOT NULL,
        field TEXT NOT NULL,
        day TEXT NOT NULL,
        first_seen TEXT NOT NULL,
        last_seen TEXT NOT NULL,
        n INTEGER NOT NULL,
        PRIMARY KEY (source_key, field, day)
      );

      CREATE TABLE tock_labels (
        run_id TEXT NOT NULL,
        dim TEXT NOT NULL,
        value TEXT NOT NULL,
        label TEXT NOT NULL,
        captured_at TEXT NOT NULL,
        PRIMARY KEY (run_id, dim, value)
      );

      CREATE TABLE tock_observations (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        field TEXT NOT NULL,
        present_count INTEGER NOT NULL,
        null_count INTEGER NOT NULL,
        inferred_type TEXT NOT NULL,
        distinct_estimate INTEGER NOT NULL,
        declared INTEGER NOT NULL,
        UNIQUE (run_id, field)
      );

      CREATE TABLE tock_rollups (
        source_key TEXT NOT NULL,
        grain TEXT NOT NULL,
        dim_set TEXT NOT NULL,
        period_ts INTEGER NOT NULL,
        dim1 TEXT NOT NULL,
        dim2 TEXT NOT NULL,
        run_id TEXT NOT NULL,
        events INTEGER NOT NULL,
        measure TEXT,
        unit TEXT,
        PRIMARY KEY (source_key, grain, dim_set, period_ts, dim1, dim2)
      );

      CREATE TABLE tock_rows (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        occurred_at TEXT NOT NULL,
        subject_key TEXT NOT NULL,
        dims_json TEXT NOT NULL,
        metrics_json TEXT NOT NULL
      );

      CREATE TABLE tock_rule_states (
        id TEXT PRIMARY KEY NOT NULL,
        run_id TEXT NOT NULL REFERENCES tock_runs(id),
        rule_kind TEXT NOT NULL CHECK (rule_kind IN ('bot_list','threshold','dedup_window','salt')),
        identifier TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        captured_at TEXT NOT NULL,
        UNIQUE (run_id, rule_kind)
      );

      CREATE TABLE tock_runs (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        schema_version INTEGER,
        filename TEXT NOT NULL,
        byte_size INTEGER NOT NULL,
        content_hash TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('received','profiled','mapped','counted','failed')),
        period_from TEXT NOT NULL,
        period_to TEXT NOT NULL,
        row_count INTEGER,
        rejected_count INTEGER,
        received_at TEXT NOT NULL,
        received_by TEXT NOT NULL,
        counted_at TEXT
      );

      CREATE TABLE tock_salts (
        day TEXT PRIMARY KEY NOT NULL,
        salt_id TEXT NOT NULL,
        secret TEXT,
        created_at TEXT NOT NULL,
        destroyed_at TEXT
      );

      CREATE TABLE tock_schemas (
        id TEXT PRIMARY KEY NOT NULL,
        source_key TEXT NOT NULL,
        version INTEGER NOT NULL,
        fields_json TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at TEXT NOT NULL,
        UNIQUE (source_key, version)
      );

      CREATE TABLE tock_source_files (
        run_id TEXT PRIMARY KEY NOT NULL REFERENCES tock_runs(id),
        content_hash TEXT NOT NULL,
        byte_size INTEGER NOT NULL,
        storage_key TEXT NOT NULL,
        stored_at TEXT NOT NULL,
        purge_after TEXT NOT NULL
      );

      CREATE TABLE tock_sources (
        key TEXT PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        expected_cadence TEXT NOT NULL,
        created_at TEXT NOT NULL
      );
    `,
  },
];
