// GENERATED by tools/client-emit.mts from spec/model.ts — do not edit by hand.
//
// Re-emit with `pnpm lint:client`; CI runs `pnpm lint:client --check` and fails on
// drift, so the client cannot fall behind the model the way a hand-written one did.
//
// Standalone on purpose: no imports, so the browser bundle carries no schema library
// and `tools/declared-deps.mjs` has nothing to object to.

/** A failed request. `status` is the interesting field — 403 is the permission model answering. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
    readonly body: unknown,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

/**
 * One page of a paged read, reassembled from the response.
 *
 * The BODY is the entries and always was; the walk rides in headers (#829), which is
 * what let paging be adopted without renaming a live endpoint's response. This puts
 * the two back together so a caller sees a page rather than a header protocol.
 *
 * `next` is an absolute URL to FOLLOW (RFC 8288), not a cursor to reassemble — this
 * request's filters and page size travel with it. Its absence is how the walk ends.
 */
export interface Paged<T> {
  entries: T[];
  /** Hand back to `follow()`. `null` when there is no next page. */
  next: string | null;
  /** From `X-Total-Count`, and only for a read that declares `total`. */
  total: number | null;
}

export interface ClientOptions {
  /** Prefixed to every declared path. Matches `mountOperations`' own default. */
  baseUrl?: string;
  /** Per-request headers — an auth token, or this demo's `x-principal` persona seam. */
  headers?: () => Record<string, string>;
  /** Injectable so the client works under a test harness, not only in a browser. */
  fetch?: typeof globalThis.fetch;
  /**
   * Pull a message out of an error body.
   *
   * The one thing here the model does NOT declare: a vertical picks its error
   * envelope in its own `app.onError`, so this is a best effort over the shapes in
   * use — `{ error }`, and problem+json's `detail`/`title` — and an app that
   * answers something else says so here rather than being guessed at.
   */
  errorMessage?: (body: unknown, response: Response) => string | undefined;
}

function defaultErrorMessage(body: unknown): string | undefined {
  if (typeof body !== 'object' || body === null) return undefined;
  const b = body as Record<string, unknown>;
  for (const key of ['error', 'detail', 'title', 'message']) {
    if (typeof b[key] === 'string') return b[key] as string;
  }
  return undefined;
}


/** `tock_sources` — declared in spec/model.ts. */
export interface Source {
  key: string;
  title: string;
  expected_cadence: string;
  discriminators: string | null;
  created_at: string;
}

/** `tock_variants` — declared in spec/model.ts. */
export interface Variant {
  id: string;
  source_key: string;
  key: string;
  selector: string;
  created_at: string;
}

/** `tock_schemas` — declared in spec/model.ts. */
export interface Schema {
  id: string;
  source_key: string;
  variant_key: string;
  version: number;
  fields_json: string;
  created_by: string;
  created_at: string;
}

/** `tock_runs` — declared in spec/model.ts. */
export interface Run {
  id: string;
  source_key: string;
  schema_version: number | null;
  filename: string;
  byte_size: number;
  content_hash: string;
  format: "csv" | "jsonl" | null;
  delimiter: string | null;
  time_field: string | null;
  subject_field: string | null;
  status: "received" | "profiled" | "mapped" | "counted" | "failed";
  period_from: string;
  period_to: string;
  row_count: number | null;
  rejected_count: number | null;
  received_at: string;
  received_by: string;
  counted_at: string | null;
}

/** `tock_source_files` — declared in spec/model.ts. */
export interface SourceFile {
  run_id: string;
  content_hash: string;
  byte_size: number;
  storage_key: string;
  stored_at: string;
  purge_after: string;
}

/** `tock_rule_states` — declared in spec/model.ts. */
export interface RuleState {
  id: string;
  run_id: string;
  rule_kind: "bot_list" | "threshold" | "dedup_window" | "salt" | "mapping";
  identifier: string;
  content_hash: string;
  captured_at: string;
}

/** `tock_salts` — declared in spec/model.ts. */
export interface Salt {
  day: string;
  salt_id: string;
  secret: string | null;
  created_at: string;
  destroyed_at: string | null;
}

/** `tock_observations` — declared in spec/model.ts. */
export interface Observation {
  id: string;
  run_id: string;
  variant_key: string;
  field: string;
  present_count: number;
  null_count: number;
  inferred_type: string;
  distinct_estimate: number;
  declared: number;
}

/** `tock_field_history` — declared in spec/model.ts. */
export interface FieldHistory {
  source_key: string;
  field: string;
  day: string;
  first_seen: string;
  last_seen: string;
  n: number;
}

/** `tock_rows` — declared in spec/model.ts. */
export interface Row {
  id: string;
  run_id: string;
  variant_key: string;
  occurred_at: string;
  subject_key: string;
  dims_json: string;
  metrics_json: string;
}

/** `tock_output_schemas` — declared in spec/model.ts. */
export interface OutputSchema {
  id: string;
  source_key: string;
  key: string;
  version: number;
  fields_json: string;
  created_by: string;
  created_at: string;
}

/** `tock_mappings` — declared in spec/model.ts. */
export interface Mapping {
  id: string;
  source_key: string;
  variant_key: string;
  output_key: string;
  version: number;
  rules_json: string;
  created_by: string;
  created_at: string;
}

/** `tock_rollups` — declared in spec/model.ts. */
export interface Rollup {
  source_key: string;
  output_key: string;
  grain: string;
  dim_set: string;
  period_start: string;
  dim1: string;
  dim2: string;
  run_id: string;
  events: number;
  measure: string | null;
  unit: string | null;
}

/** `tock_labels` — declared in spec/model.ts. */
export interface Label {
  run_id: string;
  dim: string;
  value: string;
  label: string;
  captured_at: string;
}

/** Every operation this vertical binds to HTTP, one method each. */
export interface TockClient {
  /**
   * Count a mapped run and freeze it
   *
   * `POST /runs/{runId}/count` — `tock/count-run`
   */
  countRun(input: { runId: string; rules?: ({ kind: "bot_list" | "threshold" | "dedup_window"; identifier: string; contentHash: string })[] }): Promise<{ id: string; source_key: string; schema_version: number | null; filename: string; byte_size: number; content_hash: string; format: "csv" | "jsonl" | null; delimiter: string | null; time_field: string | null; subject_field: string | null; status: "received" | "profiled" | "mapped" | "counted" | "failed"; period_from: string; period_to: string; row_count: number | null; rejected_count: number | null; received_at: string; received_by: string; counted_at: string | null; complete: boolean }>;

  /**
   * Declare a named stream of files
   *
   * `POST /sources` — `tock/declare-source`
   */
  declareSource(input: { key: string; title: string; expectedCadence: string }): Promise<Source>;

  /**
   * Declare the fields that tell record kinds apart, and the kinds
   *
   * `POST /sources/{sourceKey}/variants` — `tock/declare-variants`
   */
  declareVariants(input: { sourceKey: string; discriminators: string[]; variants: { selector: string[] }[] }): Promise<{ sourceKey: string; discriminators: string[]; variants: Variant[] }>;

  /**
   * Where a source declared shape and its data disagree
   *
   * `GET /sources/{sourceKey}/deviations` — `tock/deviations`
   */
  deviations(input: { sourceKey: string; schemaVersion?: number }): Promise<{ sourceKey: string; schemaVersion: number; findings: ({ kind: "undeclared_field" | "declared_never_arrived" | "type_mismatch" | "cardinality_spike" | "unmatched_records"; field: string; detail: string; firstSeen: string | null; lastSeen: string | null; runs: number })[] }>;

  /**
   * When a field started arriving, and how much history predates it
   *
   * `GET /sources/{sourceKey}/fields/coverage` — `tock/field-coverage`
   */
  fieldCoverage(input: { sourceKey: string; field: string }): Promise<{ field: string; firstSeen: string | null; lastSeen: string | null; rowsWith: number; rowsBefore: number; earliest: string | null; runsBefore: { id: string; filename: string; periodFrom: string }[] }>;

  /**
   * When a field first and last arrived, across every run
   *
   * `GET /sources/{sourceKey}/fields` — `tock/field-history`
   */
  fieldHistory(input: { sourceKey: string; field?: string; limit?: number }): Promise<{ entries: FieldHistory[]; limit: number; capped: boolean }>;

  /**
   * One run, and how it got where it is
   *
   * `GET /runs/{runId}` — `tock/get-run`
   */
  getRun(input: { runId: string }): Promise<Run>;

  /**
   * How each kind becomes an output shape
   *
   * `GET /sources/{sourceKey}/mappings` — `tock/list-mappings`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listMappings(input: { sourceKey: string }): Promise<Paged<Mapping>>;

  /**
   * What arrived in one run, field by field
   *
   * `GET /runs/{runId}/observations` — `tock/list-observations`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listObservations(input: { runId: string; declared?: boolean; variantKey?: string }): Promise<Paged<Observation>>;

  /**
   * The stable shapes declared for a source
   *
   * `GET /sources/{sourceKey}/outputs` — `tock/list-output-schemas`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listOutputSchemas(input: { sourceKey: string }): Promise<Paged<OutputSchema>>;

  /**
   * The mapped rows of one run
   *
   * `GET /runs/{runId}/rows` — `tock/list-rows`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listRows(input: { runId: string }): Promise<Paged<Row>>;

  /**
   * The runs over a source, newest first
   *
   * `GET /sources/{sourceKey}/runs` — `tock/list-runs`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listRuns(input: { sourceKey: string }): Promise<Paged<Run>>;

  /**
   * Every version of a source shape
   *
   * `GET /sources/{sourceKey}/schemas` — `tock/list-schemas`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listSchemas(input: { sourceKey: string; variantKey?: string }): Promise<Paged<Schema>>;

  /**
   * The sources in this workspace
   *
   * `GET /sources` — `tock/list-sources`
   *
   * Paged: walk it with `follow(page.next)` until `next` is `null`.
   */
  listSources(): Promise<Paged<Source>>;

  /**
   * The record kinds declared for a source
   *
   * `GET /sources/{sourceKey}/variants` — `tock/list-variants`
   */
  listVariants(input: { sourceKey: string }): Promise<{ discriminators: string[]; variants: Variant[] }>;

  /**
   * Bind a profiled run to a schema version
   *
   * `POST /runs/{runId}/map` — `tock/map-run`
   */
  mapRun(input: { runId: string; schemaVersion: number }): Promise<Run>;

  /**
   * Download the file a run was made from
   *
   * `GET /runs/{runId}/file` — `tock/read-source-file`
   */
  readSourceFile(input: { runId: string }): Promise<SourceFile>;

  /**
   * Record a delivered file and open a run over it
   *
   * `POST /sources/{sourceKey}/runs` — `tock/receive-run`
   */
  receiveRun(input: { sourceKey: string; filename: string; byteSize: number; format: "csv" | "jsonl"; delimiter: string | null; timeField: string; subjectField: string | null; contentHash: string; storageKey: string; periodFrom: string; periodTo: string }): Promise<Run>;

  /**
   * Counts for one grain and grouping over a period
   *
   * `GET /sources/{sourceKey}/report` — `tock/report`
   */
  report(input: { sourceKey: string; outputKey?: string; grain: "hour" | "day" | "month"; dimSet: string; from: string; to: string; includeUnknown?: boolean }): Promise<{ rows: ({ periodStart: string; dim1: string; dim2: string; label1: string | null; label2: string | null; events: number; measure: string | null; unit: string | null; runId: string })[]; grain: "hour" | "day" | "month"; dimSet: string }>;

  /**
   * The rules in force when a run was counted
   *
   * `GET /runs/{runId}/rules` — `tock/run-rules`
   */
  runRules(input: { runId: string }): Promise<{ entries: RuleState[] }>;

  /**
   * Map one record kind into one output shape
   *
   * `POST /sources/{sourceKey}/mappings` — `tock/save-mapping`
   */
  saveMapping(input: { sourceKey: string; variantKey?: string; outputKey: string; rules: { from: string; to: string }[] }): Promise<Mapping>;

  /**
   * Declare a stable shape that counts are built over
   *
   * `POST /sources/{sourceKey}/outputs` — `tock/save-output-schema`
   */
  saveOutputSchema(input: { sourceKey: string; key: string; fields: Record<string, { type: "text" | "int" | "decimal" | "timestamp" | "bool"; role: "dimension" | "measure" | "ignored" }> }): Promise<OutputSchema>;

  /**
   * Save the next version of a source shape
   *
   * `POST /sources/{sourceKey}/schemas` — `tock/save-schema`
   */
  saveSchema(input: { sourceKey: string; variantKey?: string; fields: Record<string, { type: "text" | "int" | "decimal" | "timestamp" | "bool"; role: "dimension" | "measure" | "ignored"; required?: boolean; labelField?: string }> }): Promise<Schema>;

  /**
   * Fetch the next page of any paged read, given a previous page's `next`.
   *
   * One method for every paged read rather than one per read: `next` is a URL that
   * already carries the filters, so there is nothing left for a caller to restate.
   */
  follow<T>(next: string): Promise<Paged<T>>;
}

/**
 * The plumbing below is deliberately untyped against the interface above, and cast
 * once at the end.
 *
 * `send` cannot know an operation's return type — it has a `Response`, not a schema
 * — so every method would otherwise need its own `as` and the file would carry
 * fourteen casts instead of one. The interface is what a caller sees, and it IS
 * derived from the model; this is the seam where a runtime that speaks `unknown`
 * meets it.
 */
type Args = Record<string, unknown>;

const omit = (input: Record<string, unknown>, keys: string[]): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(input ?? {})) if (!keys.includes(k)) out[k] = v;
  return out;
};

/** Declared fields become a query string; `undefined` is absent rather than the string "undefined". */
const query = (values: Record<string, unknown> | undefined): string => {
  if (!values) return '';
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(values)) {
    if (v === undefined || v === null) continue;
    params.set(k, String(v));
  }
  const s = params.toString();
  return s ? `?${s}` : '';
};

/**
 * The `rel="next"` URL out of an RFC 8288 `Link` header, or null.
 *
 * Only `next` is looked for because only `next` is sent: keyset paging walks one
 * way and does not know its own offset, so there is no `prev`, `first` or `last`
 * to honour. A header naming some other relation is not this walk's.
 */
const nextFrom = (header: string | null): string | null => {
  if (!header) return null;
  for (const part of header.split(',')) {
    const match = /^\s*<([^>]+)>\s*;\s*(.+)$/.exec(part);
    if (match && /rel\s*=\s*"?next"?/.test(match[2] as string)) return match[1] as string;
  }
  return null;
};

export function createClient(options: ClientOptions = {}): TockClient {
  const baseUrl = options.baseUrl ?? '/api';
  const doFetch = options.fetch ?? globalThis.fetch.bind(globalThis);
  const readMessage = options.errorMessage ?? defaultErrorMessage;

  /** One request, against a path that is ALREADY prefixed and query-stringed. */
  const raw = async (fullPath: string, method: string, body: unknown): Promise<Response> => {
    const hasBody = body !== undefined && method !== 'GET' && method !== 'DELETE';
    return await doFetch(fullPath, {
      method,
      headers: {
        ...(hasBody ? { 'content-type': 'application/json' } : {}),
        ...(options.headers?.() ?? {}),
      },
      ...(hasBody ? { body: JSON.stringify(body) } : {}),
    });
  };

  const parse = async (res: Response): Promise<unknown> => {
    const text = await res.text();
    const body: unknown = text ? JSON.parse(text) : null;
    if (!res.ok) throw new ApiError(res.status, readMessage(body, res) ?? res.statusText, body);
    return body;
  };

  const send = async (path: string, method: string, body: unknown, params: unknown): Promise<unknown> =>
    await parse(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  /**
   * A paged read: the entries come from the body, the walk from the headers.
   *
   * A cross-origin caller reads neither header without `Access-Control-Expose-Headers`,
   * and the symptom is not an error — it is a list that looks like it has one page. Under
   * a same-origin dev proxy (this demo) or a same-origin deployment, both are readable.
   */
  const readPage = async (res: Response): Promise<Paged<unknown>> => {
    const entries = (await parse(res)) as unknown[];
    const total = res.headers.get('X-Total-Count');
    return { entries, next: nextFrom(res.headers.get('Link')), total: total === null ? null : Number(total) };
  };

  const page = async (path: string, method: string, body: unknown, params: unknown): Promise<Paged<unknown>> =>
    await readPage(await raw(`${baseUrl}${path}${query(params as Record<string, unknown>)}`, method, body));

  return {
    countRun: (input: Args) =>
      send(`/runs/${encodeURIComponent(String(input.runId))}/count`, "POST", omit(input, ["runId"]), undefined),
    declareSource: (input: Args) =>
      send("/sources", "POST", input, undefined),
    declareVariants: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/variants`, "POST", omit(input, ["sourceKey"]), undefined),
    deviations: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/deviations`, "GET", undefined, omit(input, ["sourceKey"])),
    fieldCoverage: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/fields/coverage`, "GET", undefined, omit(input, ["sourceKey"])),
    fieldHistory: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/fields`, "GET", undefined, omit(input, ["sourceKey"])),
    getRun: (input: Args) =>
      send(`/runs/${encodeURIComponent(String(input.runId))}`, "GET", undefined, omit(input, ["runId"])),
    listMappings: (input: Args) =>
      page(`/sources/${encodeURIComponent(String(input.sourceKey))}/mappings`, "GET", undefined, omit(input, ["sourceKey"])),
    listObservations: (input: Args) =>
      page(`/runs/${encodeURIComponent(String(input.runId))}/observations`, "GET", undefined, omit(input, ["runId"])),
    listOutputSchemas: (input: Args) =>
      page(`/sources/${encodeURIComponent(String(input.sourceKey))}/outputs`, "GET", undefined, omit(input, ["sourceKey"])),
    listRows: (input: Args) =>
      page(`/runs/${encodeURIComponent(String(input.runId))}/rows`, "GET", undefined, omit(input, ["runId"])),
    listRuns: (input: Args) =>
      page(`/sources/${encodeURIComponent(String(input.sourceKey))}/runs`, "GET", undefined, omit(input, ["sourceKey"])),
    listSchemas: (input: Args) =>
      page(`/sources/${encodeURIComponent(String(input.sourceKey))}/schemas`, "GET", undefined, omit(input, ["sourceKey"])),
    listSources: () =>
      page("/sources", "GET", undefined, undefined),
    listVariants: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/variants`, "GET", undefined, omit(input, ["sourceKey"])),
    mapRun: (input: Args) =>
      send(`/runs/${encodeURIComponent(String(input.runId))}/map`, "POST", omit(input, ["runId"]), undefined),
    readSourceFile: (input: Args) =>
      send(`/runs/${encodeURIComponent(String(input.runId))}/file`, "GET", undefined, omit(input, ["runId"])),
    receiveRun: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/runs`, "POST", omit(input, ["sourceKey"]), undefined),
    report: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/report`, "GET", undefined, omit(input, ["sourceKey"])),
    runRules: (input: Args) =>
      send(`/runs/${encodeURIComponent(String(input.runId))}/rules`, "GET", undefined, omit(input, ["runId"])),
    saveMapping: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/mappings`, "POST", omit(input, ["sourceKey"]), undefined),
    saveOutputSchema: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/outputs`, "POST", omit(input, ["sourceKey"]), undefined),
    saveSchema: (input: Args) =>
      send(`/sources/${encodeURIComponent(String(input.sourceKey))}/schemas`, "POST", omit(input, ["sourceKey"]), undefined),
    follow: async (next: string) => {
      // The link names the API's OWN origin, which under a dev proxy is not the origin
      // this page was served from. So the path is kept and the origin is taken from
      // whatever this client was configured to talk to: relative for a browser, which
      // keeps the request same-origin, absolute for a harness that has no page.
      const link = new URL(next, 'http://substrat.invalid');
      const target = /^https?:\/\//.test(baseUrl)
        ? new URL(link.pathname + link.search, baseUrl).href
        : link.pathname + link.search;
      return await readPage(await raw(target, 'GET', undefined));
    },
  } as unknown as TockClient;
}
