#!/usr/bin/env node
/**
 * The three marks, enforced (#987).
 *
 * CLAUDE.md: *"A file derived from something else in the repo is worth nothing if a
 * reader cannot tell it apart from one a person maintains — and worth less than nothing
 * if it says it is generated while nothing re-emits it."* Three marks follow: the
 * `.generated.*` suffix (or a `<!-- GENERATED … -->` first line, for a document), a
 * header naming the producer and the source, and a `--check` re-emit in CI.
 *
 * Mark 3 has always been enforced — by the gates themselves. Marks 1 and 2 were prose,
 * and prose drifted: #987 found six files short of one or the other, and
 * `packages/psl/src/data.ts` carried a producer header and no suffix for a year while
 * CLAUDE.md asserted it had both.
 *
 * So this checks the two halves nothing was checking, in both directions:
 *
 *   1. A file that SAYS it is generated carries the suffix (or the documented
 *      alternative for its kind).
 *   2. A file NAMED `*.generated.*` says who generated it and from what.
 *
 * It does not check mark 3. Whether a gate exists is a fact about `package.json` and
 * CI, not about the file, and inferring it from a name would be the same guess this
 * tool exists to stop.
 *
 * Exit 1 on a problem, naming the file and the remedy. Exit 0 prints a one-line count.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, resolve, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Never walked: build output, dependencies, and the gitignored builder scratch. */
const SKIP_DIRS = new Set(['node_modules', 'dist', '.git', '.turbo', 'coverage', '.wrangler', 'projects']);

/** Extensions whose files can carry a comment, and so can carry mark 2 themselves. */
const COMMENTABLE = new Set(['.ts', '.tsx', '.mts', '.mjs', '.js', '.md', '.css', '.sql']);

/**
 * Suffixed artifacts that CANNOT carry a comment — JSON — so mark 2 lives here instead,
 * as the producer named beside the path. A `*.generated.json` absent from this list is
 * a fault: the suffix claims generation and nothing says by what. (`model.json`,
 * `openapi.json` and `.claude/launch.json` are the other accepted shape CLAUDE.md names
 * — mark 3 only, no suffix — and are not this tool's to judge.)
 */
const COMMENTLESS = new Map([
  ['scripts/lake/outbox-stream-schema.generated.json', 'tools/lake-schema-emit.mjs (pnpm lint:lake-schema)'],
]);

/** How far in a file the marker may be. Past this it is not "the first line" in any sense. */
const HEAD_BYTES = 600;

/**
 * A file that DECLARES it is generated. Deliberately a narrow phrase: the word
 * "generated" appears in ordinary prose all over this repo, and matching it loosely
 * would make the tool a nuisance nobody runs. The producer header CLAUDE.md specifies
 * starts `GENERATED by <producer>`, so that is the signal.
 */
const DECLARES = /(^|\n)\s*(\/\/|\/\*|\*|#|<!--)?\s*GENERATED by\s+\S/;

/**
 * Mark 2 in full: the producer AND the source — `GENERATED by <tool> from <source>`.
 * "By whom" alone leaves a reader at the emitter with no idea which file to edit
 * instead, which is the question the header exists to answer. The `from` may sit on
 * the next line (the conformance header wraps), so it is sought within the head rather
 * than on the first line only; it may not be another header's, so the reach is short.
 */
const NAMES_SOURCE = /GENERATED by\s+\S+[^]{0,160}?\bfrom\s+\S/;

/**
 * Files that legitimately say "GENERATED by" without being generated themselves: the
 * emitters, which contain the header they WRITE, and this tool. Exact paths and
 * per-project patterns only — no directory-wide pass. A blanket `scripts/` exemption
 * once matched `plugin/substrat/scripts/session-start.mjs`, an emitted file with no
 * suffix: precisely the missing-mark case #987 reported, accepted in silence.
 */
const EMITS_THE_HEADER = [
  /^tools\/[^/]+\.(mjs|mts)$/,
  /^packages\/psl\/scripts\/build-data\.mjs$/,
  /^packages\/model-providers\/scripts\/update-rate-card\.mjs$/,
  /^packages\/model-emit\/src\/emit-client\.ts$/,
  /^packages\/model-emit\/test\/emit-client\.test\.ts$/,
  /^apps\/docs\/\.vitepress\/headers\.mts$/,
  /^demos\/[^/]+\/scripts\/gen-assets\.mjs$/,
  /^demos\/auth-server\/scripts\/gen-schema\.mts$/,
  /^demos\/[^/]+\/tools\/emit-migrations\.mts$/,
];

const problems = [];
let declared = 0;
let suffixed = 0;

function walk(dir) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry) || entry.startsWith('.') && entry !== '.claude') continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      walk(full);
      continue;
    }
    const rel = relative(ROOT, full);
    const name = basename(full);
    const ext = name.slice(name.lastIndexOf('.'));
    const isSuffixed = /\.generated\.[^.]+$/.test(name);

    // The suffix is judged BEFORE the extension filter, or a commentless artifact
    // would slip past both checks by being unable to carry the second mark.
    if (!COMMENTABLE.has(ext)) {
      if (isSuffixed) {
        suffixed += 1;
        if (!COMMENTLESS.has(rel)) {
          problems.push(
            `${rel}: named \`.generated\` but cannot carry a header — add it to COMMENTLESS in tools/generated-marks.mjs naming its producer, so the name still says where the change is made.`,
          );
        }
      }
      continue;
    }

    let head;
    try {
      head = readFileSync(full, 'utf8').slice(0, HEAD_BYTES);
    } catch {
      continue;
    }
    const saysGenerated = DECLARES.test(head);
    const exempt = EMITS_THE_HEADER.some((re) => re.test(rel));

    if (saysGenerated && !exempt) {
      declared += 1;
      // Mark 1. A document may carry the marker instead of the suffix — CLAUDE.md's
      // stated alternative, since a `.generated.md` would read oddly in a docs nav.
      const markerIsEnough = ext === '.md';
      if (!isSuffixed && !markerIsEnough) {
        problems.push(
          `${rel}: names a producer but has no \`.generated\` suffix — mark 1 is the signal a reviewer reads in a PR diff without opening the file. Rename to \`${name.replace(ext, `.generated${ext}`)}\` and update its importers and its emitter's output path.`,
        );
      }
    }

    if (isSuffixed) {
      suffixed += 1;
      // Mark 2, the other direction: a file whose NAME claims generation has to say
      // by what, or a reader cannot find the source to edit instead.
      if (!saysGenerated) {
        problems.push(
          `${rel}: named \`.generated\` but names no producer — add a first-line header \`GENERATED by <tool> from <source> — do not edit by hand.\` so the file says where to make the change.`,
        );
      }
    }

    // Mark 2's second half, on every file that declares — suffixed or marker-form: the
    // header names the SOURCE, not only the tool. `GENERATED by x.mjs — do not edit`
    // sends a reader to the emitter and stops there.
    if (saysGenerated && !exempt && !NAMES_SOURCE.test(head)) {
      problems.push(
        `${rel}: names a producer but no source — the header reads \`GENERATED by <tool> from <source>\`, and it is the source a reader needs, since that is the file to edit instead.`,
      );
    }
  }
}

walk(ROOT);

if (problems.length > 0) {
  console.error(`✗ generated-marks: ${problems.length} problem(s)\n`);
  for (const p of problems) console.error(`  ${p}\n`);
  console.error(
    'The three marks are in CLAUDE.md: the suffix, the producer header, and a --check in CI.\n' +
      'This tool checks the first two. Mark 3 is whether a gate exists, which is a fact about\n' +
      'package.json rather than about the file — it is not inferred here.',
  );
  process.exit(1);
}

console.log(
  `generated-marks: ${declared} file(s) name a producer and source, ${suffixed} carry the suffix — marks 1 and 2 hold`,
);
