#!/usr/bin/env node
/**
 * The three marks, enforced (#987).
 *
 * CLAUDE.md: *"A file derived from something else in the repo is worth nothing if a
 * reader cannot tell it apart from one a person maintains — and worth less than nothing
 * if it says it is generated while nothing re-emits it."* Three marks follow: the
 * `.generated.*` suffix (or a `<!-- GENERATED … -->` first line, for a document), a
 * header naming the producer and the source, and a `--check` re-emit in CI.
 *
 * Mark 3 has always been enforced — by the gates themselves. Marks 1 and 2 were prose,
 * and prose drifted: #987 found six files short of one or the other, and
 * `packages/psl/src/data.ts` carried a producer header and no suffix for a year while
 * CLAUDE.md asserted it had both.
 *
 * So this checks the two halves nothing was checking, in both directions:
 *
 *   1. A file that SAYS it is generated carries the suffix (or the documented
 *      alternative for its kind).
 *   2. A file NAMED `*.generated.*` says who generated it and from what.
 *
 * It does not check mark 3. Whether a gate exists is a fact about `package.json` and
 * CI, not about the file, and inferring it from a name would be the same guess this
 * tool exists to stop.
 *
 * Exit 1 on a problem, naming the file and the remedy. Exit 0 prints a one-line count.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, resolve, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Never walked: build output, dependencies, and the gitignored builder scratch. */
const SKIP_DIRS = new Set(['node_modules', 'dist', '.git', '.turbo', 'coverage', '.wrangler', 'projects']);

/**
 * Extensions whose files can carry a comment. A JSON artifact cannot, which is the one
 * accepted shape CLAUDE.md names: `model.json`, `openapi.json`, `.claude/launch.json`
 * have mark 3 only, and are out of scope here rather than reported as faults.
 */
const COMMENTABLE = new Set(['.ts', '.tsx', '.mts', '.mjs', '.js', '.md', '.css', '.sql']);

/** How far in a file the marker may be. Past this it is not "the first line" in any sense. */
const HEAD_BYTES = 600;

/**
 * A file that DECLARES it is generated. Deliberately a narrow phrase: the word
 * "generated" appears in ordinary prose all over this repo, and matching it loosely
 * would make the tool a nuisance nobody runs. The producer header CLAUDE.md specifies
 * starts `GENERATED by`, so that is the signal.
 */
const DECLARES = /(^|\n)\s*(\/\/|\/\*|\*|#|<!--)?\s*GENERATED by\s/;

/**
 * Files that legitimately say "GENERATED by" without being generated themselves —
 * the emitters, which contain the header they WRITE, and the docs describing the rule.
 * Matched on path so a new emitter has to be added deliberately.
 */
const EMITS_THE_HEADER = [
  /^tools\//,
  /^docs\//,
  /^apps\/docs\//,
  /^CLAUDE\.md$/,
  /^packages\/create-substrat\/template\/AGENTS\.md$/,
  /scripts\/.*\.(mjs|mts)$/,
];

const problems = [];
let declared = 0;
let suffixed = 0;

function walk(dir) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry) || entry.startsWith('.') && entry !== '.claude') continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      walk(full);
      continue;
    }
    const rel = relative(ROOT, full);
    const name = basename(full);
    const ext = name.slice(name.lastIndexOf('.'));
    if (!COMMENTABLE.has(ext)) continue;

    const isSuffixed = /\.generated\.[^.]+$/.test(name);
    let head;
    try {
      head = readFileSync(full, 'utf8').slice(0, HEAD_BYTES);
    } catch {
      continue;
    }
    const saysGenerated = DECLARES.test(head);
    const exempt = EMITS_THE_HEADER.some((re) => re.test(rel));

    if (saysGenerated && !exempt) {
      declared += 1;
      // Mark 1. A document may carry the marker instead of the suffix — CLAUDE.md's
      // stated alternative, since a `.generated.md` would read oddly in a docs nav.
      const markerIsEnough = ext === '.md';
      if (!isSuffixed && !markerIsEnough) {
        problems.push(
          `${rel}: names a producer but has no \`.generated\` suffix — mark 1 is the signal a reviewer reads in a PR diff without opening the file. Rename to \`${name.replace(ext, `.generated${ext}`)}\` and update its importers and its emitter's output path.`,
        );
      }
    }

    if (isSuffixed) {
      suffixed += 1;
      // Mark 2, the other direction: a file whose NAME claims generation has to say
      // by what, or a reader cannot find the source to edit instead.
      if (!saysGenerated) {
        problems.push(
          `${rel}: named \`.generated\` but names no producer — add a first-line header \`GENERATED by <tool> from <source> — do not edit by hand.\` so the file says where to make the change.`,
        );
      }
    }
  }
}

walk(ROOT);

if (problems.length > 0) {
  console.error(`✗ generated-marks: ${problems.length} problem(s)\n`);
  for (const p of problems) console.error(`  ${p}\n`);
  console.error(
    'The three marks are in CLAUDE.md: the suffix, the producer header, and a --check in CI.\n' +
      'This tool checks the first two. Mark 3 is whether a gate exists, which is a fact about\n' +
      'package.json rather than about the file — it is not inferred here.',
  );
  process.exit(1);
}

console.log(
  `generated-marks: ${declared} file(s) name a producer, ${suffixed} carry the suffix — marks 1 and 2 hold`,
);
