#!/usr/bin/env tsx
/**
 * The platform's entry module (#1893) — what the control plane uploads in FRONT of every
 * vertical's bundle, so every deployed request is stamped by the platform rather than by
 * each vertical remembering to mount `invocationLog`.
 *
 * The bundle a vertical pushes is already built, so the entry cannot import the kernel at
 * run time: it has to be a self-contained module. It is built HERE, from the kernel's own
 * `withInvocationLog`, so there is one definition of the stamp — and emitted as a string
 * constant into `packages/control-plane-api/src/platform-entry.generated.ts`, which the
 * uploader writes into the upload with the vertical's entry name filled in.
 *
 *   pnpm lint:platform-entry            re-emit from the kernel source
 *   pnpm lint:platform-entry --check    CI: exit 1 on drift (a kernel change not re-emitted)
 *
 * Kept small on purpose: the kernel files it pulls in import nothing at run time beyond
 * each other (`routed-node.ts` checks ids with a pattern rather than the contracts schemas
 * for exactly this reason), and a size ceiling below refuses a bundle that grew a runtime
 * dependency by accident — every byte here is added to every vertical's upload.
 */
import { build } from 'esbuild';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = 'packages/control-plane-api/src/platform-entry.generated.ts';
const SOURCE = 'packages/kernel/src/invocation-log.ts';
const PLACEHOLDER = '__SUBSTRAT_VERTICAL_ENTRY__';
/** Refuse a bundle past this: it would mean a runtime dependency crept in. */
const CEILING_BYTES = 32_000;

const check = process.argv.includes('--check');

const result = await build({
  stdin: {
    contents: [
      `import { withInvocationLog } from './${SOURCE}';`,
      `import * as vertical from '${PLACEHOLDER}';`,
      `export * from '${PLACEHOLDER}';`,
      // The same two answers every vertical gives \`readRoutedNode\`: the router's secret, which
      // the platform puts on every pushed script, and the local dev opt-out.
      `export default withInvocationLog(vertical.default, {`,
      `  routerSecret: (env) => env.ROUTER_SECRET,`,
      `  allowUnsigned: (env) => env.ALLOW_DEV_NODE === 'true',`,
      `});`,
    ].join('\n'),
    resolveDir: ROOT,
    loader: 'ts',
    sourcefile: 'substrat-platform-entry.ts',
  },
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  write: false,
  external: [PLACEHOLDER],
  legalComments: 'none',
  charset: 'utf8',
  logLevel: 'silent',
});
const js = result.outputFiles[0]!.text;
if (js.length > CEILING_BYTES) {
  console.error(
    `platform-entry: the entry bundles to ${js.length} bytes, past the ${CEILING_BYTES}-byte ceiling.\n` +
      `  Every byte is added to every vertical's upload. Something in ${SOURCE}'s import graph\n` +
      `  gained a runtime dependency — make it a type-only import, or keep it out of the stamp.`,
  );
  process.exit(1);
}
if (!js.includes(PLACEHOLDER)) {
  console.error(`platform-entry: the bundle no longer names ${PLACEHOLDER}, so the uploader cannot fill it in.`);
  process.exit(2);
}

const generated = `// GENERATED by tools/platform-entry-emit.mts from ${SOURCE} — do not edit by hand.
// Re-emit with \`pnpm lint:platform-entry\`; CI runs it with \`--check\`.

/**
 * The platform's entry module (#1893): uploaded in front of a vertical's bundle and made its
 * \`main_module\`, so every request the vertical serves is stamped (\`withInvocationLog\`) before
 * the vertical sees it. \`${PLACEHOLDER}\` is replaced with the bundle's own entry; its default
 * export is wrapped and every named export (Durable Object classes, entrypoints) passes through.
 */
export const PLATFORM_ENTRY_MODULE = 'substrat-platform-entry.js';

/** The import specifier the uploader replaces with \`./<the bundle's entry>\`. */
export const PLATFORM_ENTRY_PLACEHOLDER = '${PLACEHOLDER}';

/** The entry itself — ${js.length} bytes of ESM. */
export const PLATFORM_ENTRY_SOURCE: string = ${JSON.stringify(js)};
`;

const outPath = join(ROOT, OUT);
const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
if (current === generated) {
  console.log(`platform-entry: ${OUT} is current (${js.length} bytes).`);
  process.exit(0);
}
if (check) {
  console.error(
    `platform-entry: ${OUT} is not what ${SOURCE} builds to.\n` +
      `  The stamp every vertical is deployed behind changed without being re-emitted.\n` +
      `  Run \`pnpm lint:platform-entry\` and commit the result.`,
  );
  process.exit(1);
}
writeFileSync(outPath, generated);
console.log(`platform-entry: wrote ${OUT} (${js.length} bytes).`);
