#!/usr/bin/env node
/**
 * The template's workspace call site (#878) — materialize `create-substrat`'s
 * template into a workspace member so a compiler finally sees it.
 *
 * ## The gap this closes
 *
 * `packages/create-substrat/template` is a call site of every engine surface it
 * imports, and it was the one call site nothing in the repo compiled. So a
 * non-additive engine change could be correct, reviewed, merged and released and
 * still reach `npm create substrat` broken, with nothing red until after publish.
 * It happened: #811/#855 moved `listOrders(ctx, status?)` to
 * `listOrders(ctx, page)`, `lint:pins` advanced the template's pins in the same
 * Version-packages PR, and `create-substrat@0.7.1` shipped a scaffold that failed
 * ALL THREE gates it ships with — 4 of 9 scenario tests, 2 type errors, 1 boundary
 * violation. #874 fixed that instance; this is the check that makes it the last one.
 *
 * ## Why this is NOT `lint:scaffold` (#797) a second time
 *
 * They ask different questions and only one of them can run on a PR:
 *
 *   scaffold.yml   packages from the REGISTRY   "does a real npm install work?"
 *                                               post-release only, and correctly so
 *   this           packages from the WORKSPACE  "does the template's source still
 *                                               match the surface we are about to
 *                                               ship?"  every PR
 *
 * Between a merge that adds a surface and the release that publishes it, the
 * template legitimately runs AHEAD of npm — #812 put `ctx.now()` in the template
 * while the pins still said `^0.83.0`. That is why scaffold-check has no
 * `pull_request` trigger, and it is exactly the state this check is happy in: it
 * compiles against the code the PR actually changes, which is the point. #811 would
 * have gone red in its own PR, beside the eleven other call sites it fixed.
 *
 * ## Why the files are COPIED
 *
 * `packages/create-substrat/template` stays a non-member, deliberately (#797): its
 * job is to prove an npm install with no workspace links, and a member resolves
 * `@substrat-run/*` to the workspace — the failure mode we just had, in a new
 * costume. So the sources are copied into `packages/template-check`, which owns the
 * links instead. TypeScript resolves modules from the importing FILE's directory, so
 * a symlink or an `include` pointing at the template would resolve nothing; the copy
 * is what puts the code somewhere the workspace graph reaches.
 *
 * The copy is generated, gitignored and rewritten on every run — never edited. It
 * carries the `.generated` marks in spirit and not in filename (CLAUDE.md), because
 * the filenames must stay identical to the template's for the tsconfigs to apply.
 *
 * ## What it compiles it WITH
 *
 * The tsconfigs are the real ones: `tsconfig.worker.json` is copied verbatim from
 * the template, and `tsconfig.json` / `vitest.config.ts` come from
 * `create-substrat/project-files.js` — the same module `index.js` writes a scaffold
 * from, so the two cannot drift.
 *
 * One honest difference: the member builds on the workspace's TypeScript, while a
 * scaffold pins `^5.6.0`. Compiler-version compatibility is scaffold.yml's question,
 * against the real installed toolchain; this one is about the SURFACE.
 *
 *   node tools/template-sync.mjs      materialize (idempotent; run by the member's
 *                                     own typecheck/test scripts and by boundary-lint)
 */
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { TSCONFIG, VITEST_CONFIG } from '../packages/create-substrat/project-files.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TEMPLATE = join(ROOT, 'packages', 'create-substrat', 'template');
export const CHECK_DIR = join(ROOT, 'packages', 'template-check');

/** The generated banner every materialized file is preceded by in the reader's mind. */
const NOTE = `# GENERATED by tools/template-sync.mjs from packages/create-substrat/template
# Do not edit — this directory is rewritten on every run and gitignored. Edit the
# template instead. See the header of tools/template-sync.mjs for why it is a copy.
`;

export function syncTemplate() {
  if (!existsSync(join(TEMPLATE, 'src'))) {
    process.stderr.write('template-sync: packages/create-substrat/template/src is missing\n');
    process.exit(2);
  }

  mkdirSync(CHECK_DIR, { recursive: true });

  // Rewritten wholesale, so a file DELETED from the template does not linger here
  // and keep compiling — a stale copy that passes is the failure this exists to stop.
  for (const dir of ['src', 'test']) {
    rmSync(join(CHECK_DIR, dir), { recursive: true, force: true });
    cpSync(join(TEMPLATE, dir), join(CHECK_DIR, dir), { recursive: true });
  }

  // The worker config is a real file in the template; the other two are generated
  // for a scaffold, so they come from the module that generates them.
  cpSync(join(TEMPLATE, 'tsconfig.worker.json'), join(CHECK_DIR, 'tsconfig.worker.json'));
  writeFileSync(join(CHECK_DIR, 'tsconfig.json'), TSCONFIG);
  writeFileSync(join(CHECK_DIR, 'vitest.config.ts'), VITEST_CONFIG);
  writeFileSync(join(CHECK_DIR, 'GENERATED.md'), NOTE);

  return CHECK_DIR;
}

if (resolve(process.argv[1] ?? '') === resolve(fileURLToPath(import.meta.url))) {
  syncTemplate();
}
