/**
 * The journal — derived, appended to, never rewritten.
 *
 * Nobody writes the version number: `planMigration` reconstructs what the
 * journal has already applied, diffs it against the model, and appends exactly
 * one entry when they differ. Run it after any change to `spec/model.ts`:
 *
 *     pnpm --filter @substrat-run/demo-ticket0 emit:migrations
 *     pnpm --filter @substrat-run/demo-ticket0 emit:migrations --check
 *
 * `--check` is the CI half, and it asks TWO questions, because there are two ways
 * to get out of step:
 *
 *   1. Is the journal behind the model? A schema change must not merge without its
 *      migration appearing in the diff.
 *   2. Does `src/migrations.generated.ts` still match the journal? The file says
 *      "do not edit" and until now nothing checked that anyone obeyed it — the
 *      module was rendered only on the run that appended an entry, so a hand-edit
 *      to shipped SQL passed every gate in the repo.
 *
 * The second is why the module is re-rendered on every run rather than only when
 * the plan appends: a generated file with no re-emit is a generated file only by
 * reputation.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { parseJournal, planMigration, type Journal } from '@substrat-run/model-emit';
import { ticket0Entities } from '../spec/model.js';

const check = process.argv.includes('--check');
const journalPath = new URL('../journal.json', import.meta.url);
const modulePath = new URL('../src/migrations.generated.ts', import.meta.url);

const journal: Journal = existsSync(journalPath)
  ? parseJournal(JSON.parse(readFileSync(journalPath, 'utf8')))
  : { entries: [] };

const plan = planMigration(ticket0Entities, journal);

if (plan.kind === 'refused') {
  process.stderr.write('emit-migrations: refused — this is a decision, not a diff\n\n');
  for (const r of plan.reasons) process.stderr.write(`  • ${r}\n\n`);
  process.exit(2);
}

if (check && plan.kind === 'append') {
  process.stderr.write(
    `emit-migrations: the journal is behind the model — ${plan.entry.slug} is unapplied.\n` +
      '  Run `pnpm --filter @substrat-run/demo-ticket0 emit:migrations` and commit the result,\n' +
      '  so the migration appears in the pull request rather than in a console nobody opens.\n',
  );
  process.exit(1);
}

/** What the journal WILL be — unchanged when up to date, one entry longer when not. */
const next: Journal = plan.kind === 'append' ? { entries: [...journal.entries, plan.entry] } : journal;

// The runtime shape the kernel registers, rendered from the same journal.
const module = `/**
 * GENERATED by tools/emit-migrations.mts from journal.json — do not edit by hand.
 *
 * The journal is the record; this is the shape the kernel registers. Append a
 * migration by changing spec/model.ts and re-running:
 *
 *     pnpm --filter @substrat-run/demo-ticket0 emit:migrations
 *
 * CI re-emits with --check and fails on drift, so a hand-edit to shipped SQL is
 * caught here rather than at the next deploy.
 */
import type { SqlMigration } from '@substrat-run/kernel';

export const ticket0Migrations: SqlMigration[] = [
${next.entries
  .map(
    (e) => `  {
    // ${e.slug}
    version: '${e.version}',
    sql: \`
${e.sql
  .split('\n')
  .map((l) => (l ? `      ${l}` : l))
  .join('\n')}
    \`,
  },`,
  )
  .join('\n')}
];
`;

if (check) {
  const onDisk = existsSync(modulePath) ? readFileSync(modulePath, 'utf8') : null;
  if (onDisk === null) {
    process.stderr.write(
      'emit-migrations: src/migrations.generated.ts does not exist.\n' +
        '  A missing artifact is a broken setup, not drift.\n' +
        '  Remedy: run `pnpm --filter @substrat-run/demo-ticket0 emit:migrations` and commit it.\n',
    );
    process.exit(2);
  }
  if (onDisk !== module) {
    process.stderr.write(
      'emit-migrations: src/migrations.generated.ts has drifted from journal.json.\n' +
        '  The journal is the record — a migration edited in place has already shipped\n' +
        '  its old text to every scope that applied it.\n' +
        '  Remedy: run `pnpm --filter @substrat-run/demo-ticket0 emit:migrations` and commit the diff.\n',
    );
    process.exit(1);
  }
  process.stdout.write(`journal and module in sync — ${next.entries.length} entr(ies)\n`);
  process.exit(0);
}

if (plan.kind === 'append') writeFileSync(journalPath, `${JSON.stringify(next, null, 2)}\n`);
writeFileSync(modulePath, module);
process.stdout.write(
  plan.kind === 'append'
    ? `appended ${plan.entry.version}-${plan.entry.slug}\n`
    : `journal up to date — ${next.entries.length} entr(ies)\n`,
);
